"""The Quad Cortex catalog on CorOS 4.1.0, generated by the scripts in `scripts/` from a connected unit (ADR-0020)."""
from pyquadcortex.protocol.catalogs.coros_4_1_0 import models, options, params  # noqa: F401

__all__ = ["models", "params", "options"]
