"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BinaryPreset(_message.Message):
    """Recovered from Cortex Control.app  (file: Preset.proto)"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StompLabelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SingleStompLabelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class StompIsMomentaryEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        value: _builtins.bool
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CHAINS_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    LEGACY_STOMP_MODE_STOMP_DATA_FIELD_NUMBER: _builtins.int
    SCENE_TEMPO_FIELD_NUMBER: _builtins.int
    SCENE_LABELS_FIELD_NUMBER: _builtins.int
    MIDI_MESSAGES_FIELD_NUMBER: _builtins.int
    MIDI_MESSAGES_GENERAL_FIELD_NUMBER: _builtins.int
    BYPASS_FIELD_NUMBER: _builtins.int
    TEMPOPROGRAMDATA_FIELD_NUMBER: _builtins.int
    LAYOUT_CODE_1_FIELD_NUMBER: _builtins.int
    LAYOUT_CODE_2_FIELD_NUMBER: _builtins.int
    CREATED_VERSION_FIELD_NUMBER: _builtins.int
    MODIFIED_VERSION_FIELD_NUMBER: _builtins.int
    OLDEST_COMPATIBLE_VERSION_FIELD_NUMBER: _builtins.int
    CLOUD_ID_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    STOMP_MODE_ASSIGNMENTS_FIELD_NUMBER: _builtins.int
    MODEL_UPDATE_NOTIFICATIONS_FIELD_NUMBER: _builtins.int
    RECOMPILE_CODE_1_FIELD_NUMBER: _builtins.int
    RECOMPILE_CODE_2_FIELD_NUMBER: _builtins.int
    SCENE_COLORS_FIELD_NUMBER: _builtins.int
    STOMP_LABELS_FIELD_NUMBER: _builtins.int
    MIDI_MESSAGES_GENERAL_V2_FIELD_NUMBER: _builtins.int
    SINGLE_STOMP_LABELS_FIELD_NUMBER: _builtins.int
    STOMP_IS_MOMENTARY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    DATE_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    PAN_FIELD_NUMBER: _builtins.int
    DEFAULT_SCENE_FIELD_NUMBER: _builtins.int
    AUTHOR_NAME_FIELD_NUMBER: _builtins.int
    AUTHOR_ID_FIELD_NUMBER: _builtins.int
    TEMPO_FIELD_NUMBER: _builtins.int
    SIDE_CHAIN_FOLLOW_EXISTS_FIELD_NUMBER: _builtins.int
    ZSK_7182_APPLIED_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    hash: _builtins.int
    date: _builtins.str
    volume: _builtins.float
    pan: _builtins.float
    default_scene: _builtins.int
    author_name: _builtins.str
    author_id: _builtins.str
    tempo: _builtins.int
    side_chain_follow_exists: _builtins.bool
    zsk_7182_applied: _builtins.bool
    @_builtins.property
    def chains(self) -> _containers.RepeatedCompositeFieldContainer[Global___Chain]: ...
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def legacy_stomp_mode_stomp_data(self) -> _containers.RepeatedCompositeFieldContainer[Global___LegacyStompModeStompData]: ...
    @_builtins.property
    def scene_tempo(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def scene_labels(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def midi_messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___MidiMessageInfo]: ...
    @_builtins.property
    def midi_messages_general(self) -> _containers.RepeatedCompositeFieldContainer[Global___MidiMessageInfo]: ...
    @_builtins.property
    def bypass(self) -> _containers.RepeatedCompositeFieldContainer[Global___Bypass]: ...
    @_builtins.property
    def tempoProgramData(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    @_builtins.property
    def layout_code_1(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def layout_code_2(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def created_version(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def modified_version(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def oldest_compatible_version(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def cloud_id(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def description(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def stomp_mode_assignments(self) -> _containers.RepeatedCompositeFieldContainer[Global___StompModeAssignment]: ...
    @_builtins.property
    def model_update_notifications(self) -> _containers.RepeatedCompositeFieldContainer[Global___SlotNotification]: ...
    @_builtins.property
    def recompile_code_1(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def recompile_code_2(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def scene_colors(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def stomp_labels(self) -> _containers.ScalarMap[_builtins.int, _builtins.str]: ...
    @_builtins.property
    def midi_messages_general_v2(self) -> _containers.RepeatedCompositeFieldContainer[Global___MidiMessageInfo]: ...
    @_builtins.property
    def single_stomp_labels(self) -> _containers.ScalarMap[_builtins.int, _builtins.str]: ...
    @_builtins.property
    def stomp_is_momentary(self) -> _containers.ScalarMap[_builtins.int, _builtins.bool]: ...
    def __init__(
        self,
        *,
        chains: _abc.Iterable[Global___Chain] | None = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        legacy_stomp_mode_stomp_data: _abc.Iterable[Global___LegacyStompModeStompData] | None = ...,
        scene_tempo: _abc.Iterable[_builtins.int] | None = ...,
        scene_labels: _abc.Iterable[_builtins.str] | None = ...,
        midi_messages: _abc.Iterable[Global___MidiMessageInfo] | None = ...,
        midi_messages_general: _abc.Iterable[Global___MidiMessageInfo] | None = ...,
        bypass: _abc.Iterable[Global___Bypass] | None = ...,
        tempoProgramData: _abc.Iterable[Global___Model] | None = ...,
        layout_code_1: _abc.Iterable[_builtins.int] | None = ...,
        layout_code_2: _abc.Iterable[_builtins.int] | None = ...,
        created_version: _abc.Iterable[_builtins.str] | None = ...,
        modified_version: _abc.Iterable[_builtins.str] | None = ...,
        oldest_compatible_version: _abc.Iterable[_builtins.str] | None = ...,
        cloud_id: _abc.Iterable[_builtins.str] | None = ...,
        description: _abc.Iterable[_builtins.str] | None = ...,
        stomp_mode_assignments: _abc.Iterable[Global___StompModeAssignment] | None = ...,
        model_update_notifications: _abc.Iterable[Global___SlotNotification] | None = ...,
        recompile_code_1: _abc.Iterable[_builtins.int] | None = ...,
        recompile_code_2: _abc.Iterable[_builtins.int] | None = ...,
        scene_colors: _abc.Iterable[_builtins.int] | None = ...,
        stomp_labels: _abc.Mapping[_builtins.int, _builtins.str] | None = ...,
        midi_messages_general_v2: _abc.Iterable[Global___MidiMessageInfo] | None = ...,
        single_stomp_labels: _abc.Mapping[_builtins.int, _builtins.str] | None = ...,
        stomp_is_momentary: _abc.Mapping[_builtins.int, _builtins.bool] | None = ...,
        name: _builtins.str = ...,
        hash: _builtins.int = ...,
        date: _builtins.str = ...,
        volume: _builtins.float = ...,
        pan: _builtins.float = ...,
        default_scene: _builtins.int = ...,
        author_name: _builtins.str = ...,
        author_id: _builtins.str = ...,
        tempo: _builtins.int = ...,
        side_chain_follow_exists: _builtins.bool = ...,
        zsk_7182_applied: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_author_id", b"_author_id", "_author_name", b"_author_name", "_date", b"_date", "_default_scene", b"_default_scene", "_hash", b"_hash", "_name", b"_name", "_pan", b"_pan", "_side_chain_follow_exists", b"_side_chain_follow_exists", "_tempo", b"_tempo", "_volume", b"_volume", "_zsk_7182_applied", b"_zsk_7182_applied", "author_id", b"author_id", "author_name", b"author_name", "date", b"date", "default_scene", b"default_scene", "hash", b"hash", "name", b"name", "pan", b"pan", "side_chain_follow_exists", b"side_chain_follow_exists", "tempo", b"tempo", "volume", b"volume", "zsk_7182_applied", b"zsk_7182_applied"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_author_id", b"_author_id", "_author_name", b"_author_name", "_date", b"_date", "_default_scene", b"_default_scene", "_hash", b"_hash", "_name", b"_name", "_pan", b"_pan", "_side_chain_follow_exists", b"_side_chain_follow_exists", "_tempo", b"_tempo", "_volume", b"_volume", "_zsk_7182_applied", b"_zsk_7182_applied", "author_id", b"author_id", "author_name", b"author_name", "bypass", b"bypass", "chains", b"chains", "cloud_id", b"cloud_id", "created_version", b"created_version", "date", b"date", "default_scene", b"default_scene", "description", b"description", "hash", b"hash", "layout_code_1", b"layout_code_1", "layout_code_2", b"layout_code_2", "legacy_stomp_mode_stomp_data", b"legacy_stomp_mode_stomp_data", "midi_messages", b"midi_messages", "midi_messages_general", b"midi_messages_general", "midi_messages_general_v2", b"midi_messages_general_v2", "model_update_notifications", b"model_update_notifications", "modified_version", b"modified_version", "name", b"name", "oldest_compatible_version", b"oldest_compatible_version", "pan", b"pan", "recompile_code_1", b"recompile_code_1", "recompile_code_2", b"recompile_code_2", "scene_colors", b"scene_colors", "scene_labels", b"scene_labels", "scene_tempo", b"scene_tempo", "side_chain_follow_exists", b"side_chain_follow_exists", "single_stomp_labels", b"single_stomp_labels", "stomp_is_momentary", b"stomp_is_momentary", "stomp_labels", b"stomp_labels", "stomp_mode_assignments", b"stomp_mode_assignments", "tags", b"tags", "tempo", b"tempo", "tempoProgramData", b"tempoProgramData", "volume", b"volume", "zsk_7182_applied", b"zsk_7182_applied"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__author_id: _TypeAlias = _typing.Literal["author_id"]  # noqa: Y015
    _WhichOneofArgType__author_id: _TypeAlias = _typing.Literal["_author_id", b"_author_id"]  # noqa: Y015
    _WhichOneofReturnType__author_name: _TypeAlias = _typing.Literal["author_name"]  # noqa: Y015
    _WhichOneofArgType__author_name: _TypeAlias = _typing.Literal["_author_name", b"_author_name"]  # noqa: Y015
    _WhichOneofReturnType__date: _TypeAlias = _typing.Literal["date"]  # noqa: Y015
    _WhichOneofArgType__date: _TypeAlias = _typing.Literal["_date", b"_date"]  # noqa: Y015
    _WhichOneofReturnType__default_scene: _TypeAlias = _typing.Literal["default_scene"]  # noqa: Y015
    _WhichOneofArgType__default_scene: _TypeAlias = _typing.Literal["_default_scene", b"_default_scene"]  # noqa: Y015
    _WhichOneofReturnType__hash: _TypeAlias = _typing.Literal["hash"]  # noqa: Y015
    _WhichOneofArgType__hash: _TypeAlias = _typing.Literal["_hash", b"_hash"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    _WhichOneofReturnType__pan: _TypeAlias = _typing.Literal["pan"]  # noqa: Y015
    _WhichOneofArgType__pan: _TypeAlias = _typing.Literal["_pan", b"_pan"]  # noqa: Y015
    _WhichOneofReturnType__side_chain_follow_exists: _TypeAlias = _typing.Literal["side_chain_follow_exists"]  # noqa: Y015
    _WhichOneofArgType__side_chain_follow_exists: _TypeAlias = _typing.Literal["_side_chain_follow_exists", b"_side_chain_follow_exists"]  # noqa: Y015
    _WhichOneofReturnType__tempo: _TypeAlias = _typing.Literal["tempo"]  # noqa: Y015
    _WhichOneofArgType__tempo: _TypeAlias = _typing.Literal["_tempo", b"_tempo"]  # noqa: Y015
    _WhichOneofReturnType__volume: _TypeAlias = _typing.Literal["volume"]  # noqa: Y015
    _WhichOneofArgType__volume: _TypeAlias = _typing.Literal["_volume", b"_volume"]  # noqa: Y015
    _WhichOneofReturnType__zsk_7182_applied: _TypeAlias = _typing.Literal["zsk_7182_applied"]  # noqa: Y015
    _WhichOneofArgType__zsk_7182_applied: _TypeAlias = _typing.Literal["_zsk_7182_applied", b"_zsk_7182_applied"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__author_id) -> _WhichOneofReturnType__author_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__author_name) -> _WhichOneofReturnType__author_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__date) -> _WhichOneofReturnType__date | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__default_scene) -> _WhichOneofReturnType__default_scene | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hash) -> _WhichOneofReturnType__hash | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pan) -> _WhichOneofReturnType__pan | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__side_chain_follow_exists) -> _WhichOneofReturnType__side_chain_follow_exists | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__tempo) -> _WhichOneofReturnType__tempo | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__volume) -> _WhichOneofReturnType__volume | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__zsk_7182_applied) -> _WhichOneofReturnType__zsk_7182_applied | None: ...

Global___BinaryPreset: _TypeAlias = BinaryPreset  # noqa: Y015

@_typing.final
class Chain(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODELS_FIELD_NUMBER: _builtins.int
    SPLIT_CONTROL_POINTS_FIELD_NUMBER: _builtins.int
    SPLITTER_FIELD_NUMBER: _builtins.int
    MIXER_FIELD_NUMBER: _builtins.int
    OUTPUT_CONTROL_FIELD_NUMBER: _builtins.int
    SPLITBYPASS_FIELD_NUMBER: _builtins.int
    MIXBYPASS_FIELD_NUMBER: _builtins.int
    COMBINED_SPLITTER_FIELD_NUMBER: _builtins.int
    INPUT_CONTROL_FIELD_NUMBER: _builtins.int
    IN_PORTID_FIELD_NUMBER: _builtins.int
    OUT_PORTID_FIELD_NUMBER: _builtins.int
    ROW_FIELD_NUMBER: _builtins.int
    in_portid: _builtins.int
    out_portid: _builtins.int
    row: _builtins.int
    @_builtins.property
    def models(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    @_builtins.property
    def split_control_points(self) -> _containers.RepeatedCompositeFieldContainer[Global___SplitControlPoints]: ...
    @_builtins.property
    def splitter(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    @_builtins.property
    def mixer(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    @_builtins.property
    def output_control(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    @_builtins.property
    def splitBypass(self) -> _containers.RepeatedCompositeFieldContainer[Global___SceneBypass]: ...
    @_builtins.property
    def mixBypass(self) -> _containers.RepeatedCompositeFieldContainer[Global___SceneBypass]: ...
    @_builtins.property
    def combined_splitter(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    @_builtins.property
    def input_control(self) -> _containers.RepeatedCompositeFieldContainer[Global___Model]: ...
    def __init__(
        self,
        *,
        models: _abc.Iterable[Global___Model] | None = ...,
        split_control_points: _abc.Iterable[Global___SplitControlPoints] | None = ...,
        splitter: _abc.Iterable[Global___Model] | None = ...,
        mixer: _abc.Iterable[Global___Model] | None = ...,
        output_control: _abc.Iterable[Global___Model] | None = ...,
        splitBypass: _abc.Iterable[Global___SceneBypass] | None = ...,
        mixBypass: _abc.Iterable[Global___SceneBypass] | None = ...,
        combined_splitter: _abc.Iterable[Global___Model] | None = ...,
        input_control: _abc.Iterable[Global___Model] | None = ...,
        in_portid: _builtins.int = ...,
        out_portid: _builtins.int = ...,
        row: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_in_portid", b"_in_portid", "_out_portid", b"_out_portid", "_row", b"_row", "in_portid", b"in_portid", "out_portid", b"out_portid", "row", b"row"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_in_portid", b"_in_portid", "_out_portid", b"_out_portid", "_row", b"_row", "combined_splitter", b"combined_splitter", "in_portid", b"in_portid", "input_control", b"input_control", "mixBypass", b"mixBypass", "mixer", b"mixer", "models", b"models", "out_portid", b"out_portid", "output_control", b"output_control", "row", b"row", "splitBypass", b"splitBypass", "split_control_points", b"split_control_points", "splitter", b"splitter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__in_portid: _TypeAlias = _typing.Literal["in_portid"]  # noqa: Y015
    _WhichOneofArgType__in_portid: _TypeAlias = _typing.Literal["_in_portid", b"_in_portid"]  # noqa: Y015
    _WhichOneofReturnType__out_portid: _TypeAlias = _typing.Literal["out_portid"]  # noqa: Y015
    _WhichOneofArgType__out_portid: _TypeAlias = _typing.Literal["_out_portid", b"_out_portid"]  # noqa: Y015
    _WhichOneofReturnType__row: _TypeAlias = _typing.Literal["row"]  # noqa: Y015
    _WhichOneofArgType__row: _TypeAlias = _typing.Literal["_row", b"_row"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__in_portid) -> _WhichOneofReturnType__in_portid | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__out_portid) -> _WhichOneofReturnType__out_portid | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__row) -> _WhichOneofReturnType__row | None: ...

Global___Chain: _TypeAlias = Chain  # noqa: Y015

@_typing.final
class Model(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    BYPASS_EXPRESSION_FIELD_NUMBER: _builtins.int
    EXPRESSION_BYPASS_INFO_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    NOTIFY_FLAG_FIELD_NUMBER: _builtins.int
    SIDECHAIN_SINK_FLAG_FIELD_NUMBER: _builtins.int
    SIDECHAIN_SOURCE_FLAG_FIELD_NUMBER: _builtins.int
    hash: _builtins.int
    column: _builtins.int
    notify_flag: _builtins.bool
    sidechain_sink_flag: _builtins.bool
    sidechain_source_flag: _builtins.bool
    @_builtins.property
    def params(self) -> _containers.RepeatedCompositeFieldContainer[Global___Param]: ...
    @_builtins.property
    def bypass_expression(self) -> _containers.RepeatedCompositeFieldContainer[Global___Expression]: ...
    @_builtins.property
    def expression_bypass_info(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExpressionBypassInfo]: ...
    def __init__(
        self,
        *,
        params: _abc.Iterable[Global___Param] | None = ...,
        bypass_expression: _abc.Iterable[Global___Expression] | None = ...,
        expression_bypass_info: _abc.Iterable[Global___ExpressionBypassInfo] | None = ...,
        hash: _builtins.int = ...,
        column: _builtins.int = ...,
        notify_flag: _builtins.bool = ...,
        sidechain_sink_flag: _builtins.bool = ...,
        sidechain_source_flag: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_column", b"_column", "_hash", b"_hash", "_notify_flag", b"_notify_flag", "_sidechain_sink_flag", b"_sidechain_sink_flag", "_sidechain_source_flag", b"_sidechain_source_flag", "column", b"column", "hash", b"hash", "notify_flag", b"notify_flag", "sidechain_sink_flag", b"sidechain_sink_flag", "sidechain_source_flag", b"sidechain_source_flag"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_column", b"_column", "_hash", b"_hash", "_notify_flag", b"_notify_flag", "_sidechain_sink_flag", b"_sidechain_sink_flag", "_sidechain_source_flag", b"_sidechain_source_flag", "bypass_expression", b"bypass_expression", "column", b"column", "expression_bypass_info", b"expression_bypass_info", "hash", b"hash", "notify_flag", b"notify_flag", "params", b"params", "sidechain_sink_flag", b"sidechain_sink_flag", "sidechain_source_flag", b"sidechain_source_flag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__column: _TypeAlias = _typing.Literal["column"]  # noqa: Y015
    _WhichOneofArgType__column: _TypeAlias = _typing.Literal["_column", b"_column"]  # noqa: Y015
    _WhichOneofReturnType__hash: _TypeAlias = _typing.Literal["hash"]  # noqa: Y015
    _WhichOneofArgType__hash: _TypeAlias = _typing.Literal["_hash", b"_hash"]  # noqa: Y015
    _WhichOneofReturnType__notify_flag: _TypeAlias = _typing.Literal["notify_flag"]  # noqa: Y015
    _WhichOneofArgType__notify_flag: _TypeAlias = _typing.Literal["_notify_flag", b"_notify_flag"]  # noqa: Y015
    _WhichOneofReturnType__sidechain_sink_flag: _TypeAlias = _typing.Literal["sidechain_sink_flag"]  # noqa: Y015
    _WhichOneofArgType__sidechain_sink_flag: _TypeAlias = _typing.Literal["_sidechain_sink_flag", b"_sidechain_sink_flag"]  # noqa: Y015
    _WhichOneofReturnType__sidechain_source_flag: _TypeAlias = _typing.Literal["sidechain_source_flag"]  # noqa: Y015
    _WhichOneofArgType__sidechain_source_flag: _TypeAlias = _typing.Literal["_sidechain_source_flag", b"_sidechain_source_flag"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__column) -> _WhichOneofReturnType__column | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hash) -> _WhichOneofReturnType__hash | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__notify_flag) -> _WhichOneofReturnType__notify_flag | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__sidechain_sink_flag) -> _WhichOneofReturnType__sidechain_sink_flag | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__sidechain_source_flag) -> _WhichOneofReturnType__sidechain_source_flag | None: ...

Global___Model: _TypeAlias = Model  # noqa: Y015

@_typing.final
class SplitControlPoints(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPLIT_FIELD_NUMBER: _builtins.int
    MIX_FIELD_NUMBER: _builtins.int
    split: _builtins.int
    mix: _builtins.int
    def __init__(
        self,
        *,
        split: _builtins.int = ...,
        mix: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mix", b"mix", "split", b"split"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SplitControlPoints: _TypeAlias = SplitControlPoints  # noqa: Y015

@_typing.final
class Bypass(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COLBYPASS_FIELD_NUMBER: _builtins.int
    ROW_FIELD_NUMBER: _builtins.int
    row: _builtins.int
    @_builtins.property
    def colBypass(self) -> _containers.RepeatedCompositeFieldContainer[Global___ColBypass]: ...
    def __init__(
        self,
        *,
        colBypass: _abc.Iterable[Global___ColBypass] | None = ...,
        row: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_row", b"_row", "row", b"row"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_row", b"_row", "colBypass", b"colBypass", "row", b"row"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__row: _TypeAlias = _typing.Literal["row"]  # noqa: Y015
    _WhichOneofArgType__row: _TypeAlias = _typing.Literal["_row", b"_row"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__row) -> _WhichOneofReturnType__row | None: ...

Global___Bypass: _TypeAlias = Bypass  # noqa: Y015

@_typing.final
class ColBypass(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCENEBYPASS_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    SCENEMODE_FIELD_NUMBER: _builtins.int
    column: _builtins.int
    sceneMode: _builtins.bool
    @_builtins.property
    def sceneBypass(self) -> _containers.RepeatedCompositeFieldContainer[Global___SceneBypass]: ...
    def __init__(
        self,
        *,
        sceneBypass: _abc.Iterable[Global___SceneBypass] | None = ...,
        column: _builtins.int = ...,
        sceneMode: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_column", b"_column", "_sceneMode", b"_sceneMode", "column", b"column", "sceneMode", b"sceneMode"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_column", b"_column", "_sceneMode", b"_sceneMode", "column", b"column", "sceneBypass", b"sceneBypass", "sceneMode", b"sceneMode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__column: _TypeAlias = _typing.Literal["column"]  # noqa: Y015
    _WhichOneofArgType__column: _TypeAlias = _typing.Literal["_column", b"_column"]  # noqa: Y015
    _WhichOneofReturnType__sceneMode: _TypeAlias = _typing.Literal["sceneMode"]  # noqa: Y015
    _WhichOneofArgType__sceneMode: _TypeAlias = _typing.Literal["_sceneMode", b"_sceneMode"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__column) -> _WhichOneofReturnType__column | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__sceneMode) -> _WhichOneofReturnType__sceneMode | None: ...

Global___ColBypass: _TypeAlias = ColBypass  # noqa: Y015

@_typing.final
class SceneBypass(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BYPASS_FIELD_NUMBER: _builtins.int
    bypass: _builtins.bool
    def __init__(
        self,
        *,
        bypass: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bypass", b"bypass"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SceneBypass: _TypeAlias = SceneBypass  # noqa: Y015

@_typing.final
class Param(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARAM_VALUES_FIELD_NUMBER: _builtins.int
    DYNAMIC_STEPS_FIELD_NUMBER: _builtins.int
    DYNAMIC_ICONS_FIELD_NUMBER: _builtins.int
    DYNAMIC_METADATA_FIELD_NUMBER: _builtins.int
    EXPRESSION_FIELD_NUMBER: _builtins.int
    EXPRESSION_MIN_FIELD_NUMBER: _builtins.int
    EXPRESSION_MAX_FIELD_NUMBER: _builtins.int
    SCENE_MODE_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    IS_LED_FIELD_NUMBER: _builtins.int
    expression: _builtins.int
    expression_min: _builtins.float
    expression_max: _builtins.float
    scene_mode: _builtins.bool
    index: _builtins.int
    is_led: _builtins.bool
    @_builtins.property
    def param_values(self) -> _containers.RepeatedCompositeFieldContainer[Global___ParamValue]: ...
    @_builtins.property
    def dynamic_steps(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def dynamic_icons(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def dynamic_metadata(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        param_values: _abc.Iterable[Global___ParamValue] | None = ...,
        dynamic_steps: _abc.Iterable[_builtins.str] | None = ...,
        dynamic_icons: _abc.Iterable[_builtins.str] | None = ...,
        dynamic_metadata: _abc.Iterable[_builtins.str] | None = ...,
        expression: _builtins.int = ...,
        expression_min: _builtins.float = ...,
        expression_max: _builtins.float = ...,
        scene_mode: _builtins.bool = ...,
        index: _builtins.int = ...,
        is_led: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_expression", b"_expression", "_expression_max", b"_expression_max", "_expression_min", b"_expression_min", "_index", b"_index", "_is_led", b"_is_led", "_scene_mode", b"_scene_mode", "expression", b"expression", "expression_max", b"expression_max", "expression_min", b"expression_min", "index", b"index", "is_led", b"is_led", "scene_mode", b"scene_mode"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_expression", b"_expression", "_expression_max", b"_expression_max", "_expression_min", b"_expression_min", "_index", b"_index", "_is_led", b"_is_led", "_scene_mode", b"_scene_mode", "dynamic_icons", b"dynamic_icons", "dynamic_metadata", b"dynamic_metadata", "dynamic_steps", b"dynamic_steps", "expression", b"expression", "expression_max", b"expression_max", "expression_min", b"expression_min", "index", b"index", "is_led", b"is_led", "param_values", b"param_values", "scene_mode", b"scene_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__expression: _TypeAlias = _typing.Literal["expression"]  # noqa: Y015
    _WhichOneofArgType__expression: _TypeAlias = _typing.Literal["_expression", b"_expression"]  # noqa: Y015
    _WhichOneofReturnType__expression_max: _TypeAlias = _typing.Literal["expression_max"]  # noqa: Y015
    _WhichOneofArgType__expression_max: _TypeAlias = _typing.Literal["_expression_max", b"_expression_max"]  # noqa: Y015
    _WhichOneofReturnType__expression_min: _TypeAlias = _typing.Literal["expression_min"]  # noqa: Y015
    _WhichOneofArgType__expression_min: _TypeAlias = _typing.Literal["_expression_min", b"_expression_min"]  # noqa: Y015
    _WhichOneofReturnType__index: _TypeAlias = _typing.Literal["index"]  # noqa: Y015
    _WhichOneofArgType__index: _TypeAlias = _typing.Literal["_index", b"_index"]  # noqa: Y015
    _WhichOneofReturnType__is_led: _TypeAlias = _typing.Literal["is_led"]  # noqa: Y015
    _WhichOneofArgType__is_led: _TypeAlias = _typing.Literal["_is_led", b"_is_led"]  # noqa: Y015
    _WhichOneofReturnType__scene_mode: _TypeAlias = _typing.Literal["scene_mode"]  # noqa: Y015
    _WhichOneofArgType__scene_mode: _TypeAlias = _typing.Literal["_scene_mode", b"_scene_mode"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__expression) -> _WhichOneofReturnType__expression | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__expression_max) -> _WhichOneofReturnType__expression_max | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__expression_min) -> _WhichOneofReturnType__expression_min | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__index) -> _WhichOneofReturnType__index | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_led) -> _WhichOneofReturnType__is_led | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__scene_mode) -> _WhichOneofReturnType__scene_mode | None: ...

Global___Param: _TypeAlias = Param  # noqa: Y015

@_typing.final
class ParamValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INT_VALUE_FIELD_NUMBER: _builtins.int
    FLOAT_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    int_value: _builtins.int
    float_value: _builtins.float
    string_value: _builtins.str
    def __init__(
        self,
        *,
        int_value: _builtins.int = ...,
        float_value: _builtins.float = ...,
        string_value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["float_value", b"float_value", "int_value", b"int_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["float_value", b"float_value", "int_value", b"int_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["int_value", "float_value", "string_value"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___ParamValue: _TypeAlias = ParamValue  # noqa: Y015

@_typing.final
class LegacyStompModeStompData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROW_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    row: _builtins.int
    column: _builtins.int
    def __init__(
        self,
        *,
        row: _builtins.int = ...,
        column: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["column", b"column", "row", b"row"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LegacyStompModeStompData: _TypeAlias = LegacyStompModeStompData  # noqa: Y015

@_typing.final
class StompModeAssignment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROW_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    STOMP_INDEX_FIELD_NUMBER: _builtins.int
    row: _builtins.int
    column: _builtins.int
    stomp_index: _builtins.int
    def __init__(
        self,
        *,
        row: _builtins.int = ...,
        column: _builtins.int = ...,
        stomp_index: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["column", b"column", "row", b"row", "stomp_index", b"stomp_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StompModeAssignment: _TypeAlias = StompModeAssignment  # noqa: Y015

@_typing.final
class MidiMessageInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    PARAM1_FIELD_NUMBER: _builtins.int
    PARAM2_FIELD_NUMBER: _builtins.int
    PARAM3_FIELD_NUMBER: _builtins.int
    type: _builtins.int
    channel: _builtins.int
    param1: _builtins.int
    param2: _builtins.int
    param3: _builtins.int
    def __init__(
        self,
        *,
        type: _builtins.int = ...,
        channel: _builtins.int = ...,
        param1: _builtins.int = ...,
        param2: _builtins.int = ...,
        param3: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "param1", b"param1", "param2", b"param2", "param3", b"param3", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MidiMessageInfo: _TypeAlias = MidiMessageInfo  # noqa: Y015

@_typing.final
class Expression(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPRESSION_FIELD_NUMBER: _builtins.int
    EXPRESSION_MIN_FIELD_NUMBER: _builtins.int
    EXPRESSION_MAX_FIELD_NUMBER: _builtins.int
    expression: _builtins.int
    expression_min: _builtins.float
    expression_max: _builtins.float
    def __init__(
        self,
        *,
        expression: _builtins.int = ...,
        expression_min: _builtins.float = ...,
        expression_max: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expression", b"expression", "expression_max", b"expression_max", "expression_min", b"expression_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Expression: _TypeAlias = Expression  # noqa: Y015

@_typing.final
class ExpressionBypassInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    INVERT_FIELD_NUMBER: _builtins.int
    DELAY_MS_FIELD_NUMBER: _builtins.int
    LATCH_EMULATION_FIELD_NUMBER: _builtins.int
    type: _builtins.int
    invert: _builtins.bool
    delay_ms: _builtins.int
    latch_emulation: _builtins.bool
    def __init__(
        self,
        *,
        type: _builtins.int = ...,
        invert: _builtins.bool = ...,
        delay_ms: _builtins.int = ...,
        latch_emulation: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay_ms", b"delay_ms", "invert", b"invert", "latch_emulation", b"latch_emulation", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExpressionBypassInfo: _TypeAlias = ExpressionBypassInfo  # noqa: Y015

@_typing.final
class SlotNotification(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROW_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    row: _builtins.int
    column: _builtins.int
    def __init__(
        self,
        *,
        row: _builtins.int = ...,
        column: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["column", b"column", "row", b"row"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SlotNotification: _TypeAlias = SlotNotification  # noqa: Y015
