"""Generated protobuf bindings for the Quad Cortex control protocol.

The *_pb2.py modules here are generated by scripts/compile_protos.sh and are
gitignored (regenerated per machine).

protoc emits absolute sibling imports (ProductionAutomation_pb2 does
`import Preset_pb2`), which fail inside a package. Appending this directory
to sys.path lets those imports resolve without post-processing the generated
code, so plain protoc output keeps working on regeneration.
"""

import os
import sys

_here = os.path.dirname(__file__)
if _here not in sys.path:
    sys.path.append(_here)
