"""The choices a list-valued parameter offers, as enums.

GENERATED by ``scripts/generate_options.py --snapshot coros_4_0_1``. Do not edit by hand.

A list parameter stores ``index / (count - 1)`` on the wire, so picking
an option means knowing its position. These name the positions::

    qc.set_param_option(block, 'DYN MODE', options.DynMode.GATE)

110 enums cover 295 parameters, because the same list means
the same thing wherever it appears - the note-length list is shared by
``SYNC NOTE``, ``SYNC NOTE L``, ``SYNC NOTE R`` and two more.

**A two-option Off/On parameter gets no enum.** 303 parameters
offer exactly those, and ``True`` says everything ``OffOn.ON`` would::

    qc.set_param(block, 'SYNC', True)

**A dynamic list gets no enum either.** Twelve parameters build their
list from the preset - it includes one entry per upstream block - so
read those with :func:`~pyquadcortex.protocol.client.param_options`.

The member names are ours; the wire's strings are the device's, and
``OPTION_LABELS`` keeps them verbatim. Where the two differ the label is
in a comment beside the member.

**These names come from the catalog, not from the screen.** ``stepNames``
is the device's own vocabulary, and where it can be compared against what
the device RENDERS it does not match - the catalog writes ``In 1`` and
``Ret 1/2`` where the device writes ``Input 1`` and ``Return 1/2``. So
each enum says whether a human has read it off the unit, and
``OPTION_AUDIT`` publishes that for all 113 fixed lists:
13 audited, 1 drawn (read, but the unit draws pictures
rather than words), 5 not drawn at all, 0 partly, and
94 that nobody has looked at.
"""
from enum import IntEnum


class Adjust(IntEnum):
    """2 parameters use this list: Ø ADJUST, Ø ADJUST R

    On Phase Doctor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    BYPASS = 0
    N90 = 1    # '90°'
    N180 = 2    # '180°'


class AnalogDelayMSyncNote(IntEnum):
    """2 parameters use this list: SYNC NOTE

    On Analog Delay (M), Analog Delay (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1_16 = 0    # '1/16'
    N1_8T = 1    # '1/8T'
    N1_16D = 2    # '1/16D'
    N1_8 = 3    # '1/8'
    N1_4T = 4    # '1/4T'
    N1_8D = 5    # '1/8D'
    N1_4 = 6    # '1/4'
    N1_2T = 7    # '1/2T'
    N1_4D = 8    # '1/4D'
    N1_2 = 9    # '1/2'
    N1_1T = 10    # '1/1T'
    N1_2D = 11    # '1/2D'
    N1_1 = 12    # '1/1'


class ArpPattern(IntEnum):
    """1 parameter use this list: ARP PATTERN

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    UP = 0
    DOWN = 1
    UP_AND_DOWN = 2    # 'Up & Down'
    DOWN_AND_UP = 3    # 'Down & Up'
    RANDOM = 4


class BitDepth(IntEnum):
    """2 parameters use this list: BIT DEPTH

    On Bit-Crusher (ST), Bit-Crusher Engine (M).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N5 = 4    # '5'
    N6 = 5    # '6'
    N7 = 6    # '7'
    N8 = 7    # '8'
    N9 = 8    # '9'
    N10 = 9    # '10'
    N11 = 10    # '11'
    N12 = 11    # '12'
    N13 = 12    # '13'
    N14 = 13    # '14'
    N15 = 14    # '15'
    N16 = 15    # '16'


class Boost(IntEnum):
    """2 parameters use this list: BOOST

    On UK C15 TopBoost, UK C30 TopBoost.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    HOT = 0
    COOL = 1


class Bright(IntEnum):
    """1 parameter use this list: BRIGHT

    On Freeman 100 Clean.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NORMAL = 0
    BRIGHT_1 = 1    # 'Bright 1'
    BRIGHT_2 = 2    # 'Bright 2'


class Center(IntEnum):
    """2 parameters use this list: Ø CENTER, Ø CENTER R

    On Phase Doctor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LO_FREQ = 0    # 'Lo Freq'
    HI_FREQ = 1    # 'Hi Freq'


class ChannelNormal(IntEnum):
    """1 parameter use this list: CHANNEL

    On Soldano SLO-100®.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NORMAL = 0
    OD = 1


class ChiefCe2wMType(IntEnum):
    """2 parameters use this list: TYPE

    On Chief CE2W (M), Chief CE2W (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    CE2_C = 0    # 'CE2-C'
    CE1_C = 1    # 'CE1-C'
    CE1_V = 2    # 'CE1-V'


class ChiefDc2wMMode(IntEnum):
    """2 parameters use this list: MODE

    On Chief DC2W (M), Chief DC2W (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N1_2 = 4    # '1+2'
    N1_3 = 5    # '1+3'
    N1_4 = 6    # '1+4'
    N2_3 = 7    # '2+3'
    N2_4 = 8    # '2+4'
    N3_4 = 9    # '3+4'


class ChiefDc2wMType(IntEnum):
    """2 parameters use this list: TYPE

    On Chief DC2W (M), Chief DC2W (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    S = 0
    SDD_320 = 1    # 'SDD-320'


class Color(IntEnum):
    """1 parameter use this list: COLOR

    On Flanger Engine.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NATURAL = 0
    WARM = 1
    DARK = 2
    BRIGHT = 3
    SPARKLE = 4
    DUSTY = 5
    SPIKY = 6
    TWANGY = 7


class CoryWongDIFunkConsoleAttack(IntEnum):
    """1 parameter use this list: ATTACK

    On Cory Wong D.I. Funk Console.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    FAST = 0
    SLOW = 1


class CoryWongDelayYYMode(IntEnum):
    """1 parameter use this list: MODE

    On Cory Wong Delay-y-y.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SINGLE = 0
    DUAL = 1


class Crunch(IntEnum):
    """1 parameter use this list: CRUNCH

    On Soldano SLO-100®.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    CLEAN = 0
    CRUNCH = 1


class Curve(IntEnum):
    """1 parameter use this list: CURVE

    On Volume.

    Audited against the unit's screen 2026-09-14: all 2 positions read.
    """

    LINEAR = 0
    LOG = 1


class DCellHisbertCh2Mode(IntEnum):
    """1 parameter use this list: MODE

    On D-Cell Hisbert Ch2.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MINUS = 0    # '-'
    PLUS = 1    # '+'


class Decay(IntEnum):
    """1 parameter use this list: DECAY

    On Foog.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    FAST = 0
    SMOOTH = 1


class DigitalFlangerPolarity(IntEnum):
    """1 parameter use this list: POLARITY

    On Digital Flanger.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NEG = 0
    POS = 1


class DivSource(IntEnum):
    """1 parameter use this list: DIV. SOURCE

    On Phase-Locked Loop.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    UNISON = 0
    MULTIPLIER = 1


class Divider(IntEnum):
    """1 parameter use this list: DIVIDER

    On Phase-Locked Loop.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N2 = 0    # '2'
    N3 = 1    # '3'
    N4 = 2    # '4'
    N5 = 3    # '5'
    N6 = 4    # '6'
    N7 = 5    # '7'
    N8 = 6    # '8'


class DreamChorusMMode(IntEnum):
    """2 parameters use this list: MODE

    On Dream Chorus (M), Dream Chorus (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    CHO1 = 0
    CHO2 = 1


class DriveType(IntEnum):
    """2 parameters use this list: DRIVE TYPE

    On Chorus Engine, Flanger Engine.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SOFT = 0
    EDGY = 1
    HARD = 2
    OFF = 3


class DualChorusMode(IntEnum):
    """1 parameter use this list: MODE

    On Dual Chorus.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    CHORUS = 0
    VIBE = 1


class DumbbellOdsChannel(IntEnum):
    """1 parameter use this list: CHANNEL

    On Dumbbell ODS.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    CLEAN = 0
    OD = 1


class DumbbellOdsEq(IntEnum):
    """1 parameter use this list: EQ

    On Dumbbell ODS.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    JAZZ = 0
    ROCK = 1


class DuplicateMode(IntEnum):
    """1 parameter use this list: DUPLICATE MODE

    On Looper X.

    Audited against the unit's screen 2026-09-14: all 2 positions read.
    """

    FREE = 0
    SYNC = 1


class DynMode2(IntEnum):
    """9 parameters use this list: DYN MODE

    On 9 models, among them Gojira DLY, Nameless Delay, Nolly Delay-1 (M).

    NOT DRAWN by the unit, so these words cannot be held
    against a screen. Looked for on Plini Delay's DYN MODE and not
    found on any page of the block (2026-09-14). This is
    an observation, not the catalog's ``hidden`` flag - a
    list marked hidden IS drawn on a Mono Synth.
    """

    DUCK = 0    # screen: None; catalog: 'Duck'
    GATE = 1


class DynMode3(IntEnum):
    """11 parameters use this list: DYN MODE

    On 11 models, among them Analog Delay (M), Analog Delay (ST), Digital Delay (M).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    OFF = 0
    DUCK = 1
    GATE = 2


class Eq3(IntEnum):
    """8 parameters use this list: EQ

    On 8 models, among them CA 1Star Clean 100W Normal, CA 1Star Clean 100W Tweed, CA 1Star Clean 50W Normal.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NORMAL = 0
    THICK = 1
    THICKER = 2


class FeedbackMode(IntEnum):
    """2 parameters use this list: FEEDBACK MODE

    On Dual Reverse Delay, Reverse Delay (M).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    REVERSE = 0
    FLIP = 1


class Filter(IntEnum):
    """1 parameter use this list: FILTER

    On Foog.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N4_POLE = 0    # '4-POLE'
    N2_POLE = 1    # '2-POLE'


class FilterCutoff(IntEnum):
    """1 parameter use this list: FILTER CUTOFF

    On Love Meat.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LOW = 0
    A = 1
    B = 2
    HIGH = 3


class FilterType(IntEnum):
    """1 parameter use this list: FILTER TYPE

    On Love Meat.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LOWPASS = 0
    BANDPASS = 1
    HIGHPASS = 2


class FlangerEngineWaveform(IntEnum):
    """1 parameter use this list: WAVEFORM

    On Flanger Engine.

    Audited against the unit's screen 2026-09-16: all 7 positions read.
    """

    SINE = 0
    TRIANGLE = 1
    SQUARE = 2
    SAW_UP = 3    # 'Saw Up'
    SAW_DN = 4    # 'Saw Dn'
    RNDSMOOTH = 5
    RNDSTEP = 6


class Focus(IntEnum):
    """2 parameters use this list: FOCUS

    On Victor Squid Ch1, Victor Squid Ch2.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    ON = 0
    OFF = 1


class Frequency(IntEnum):
    """2 parameters use this list: FREQUENCY, UNI. AMOUNT

    On Amped Super Valve, Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N5 = 4    # '5'


class GainPolarity(IntEnum):
    """3 parameters use this list: PHASE INVERT, Ø POLARITY, Ø POLARITY R

    On Gain, Phase Doctor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NORMAL = 0
    INVERTED = 1


class GojiraWowMode(IntEnum):
    """1 parameter use this list: MODE

    On Gojira WOW.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    BLADE_2 = 0    # 'Blade 2'
    BLADE_1 = 1    # 'Blade 1'
    FATSO = 2


class HighsFreq(IntEnum):
    """1 parameter use this list: HIGHS FREQ

    On Cory Wong D.I. Funk Console.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N4_KHZ = 0    # '4 kHz'
    N2_5_KHZ = 1    # '2.5 kHz'


class HpfSlope(IntEnum):
    """2 parameters use this list: HPF SLOPE, LPF SLOPE

    On Low-High Cut.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    FLAT = 0
    MINUS_6 = 1    # '-6'
    MINUS_12 = 2    # '-12'
    MINUS_18 = 3    # '-18'
    MINUS_24 = 4    # '-24'
    MINUS_30 = 5    # '-30'
    MINUS_36 = 6    # '-36'
    MINUS_42 = 7    # '-42'
    MINUS_48 = 8    # '-48'


class Input(IntEnum):
    """2 parameters use this list: INPUT

    On US DLX 64 Vintage, US DLX 65 Reissue.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LOW = 0
    HIGH = 1


class Instrument(IntEnum):
    """1 parameter use this list: INSTRUMENT

    On Phase-Locked Loop.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    GUITAR = 0
    BASS = 1


class Invert(IntEnum):
    """16 parameters use this list: INVERT

    On 8 models, among them Dual (M), Dual (M) Lite, Dual (ST).

    NOT DRAWN by the unit, so these words cannot be held
    against a screen. Looked for on Single (M)'s INVERT and not
    found on any page of the block (2026-09-14). This is
    an observation, not the catalog's ``hidden`` flag - a
    list marked hidden IS drawn on a Mono Synth.
    """

    NORMAL = 0    # screen: None; catalog: 'Noral'
    INVERTED = 1


class Legendary87MRatio(IntEnum):
    """3 parameters use this list: RATIO

    On Legendary 87 (M), Legendary 87 (S/C), Legendary 87 (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N4 = 0    # '4'
    N8 = 1    # '8'
    N12 = 2    # '12'
    N20 = 3    # '20'
    ALL = 4


class LowsFreq(IntEnum):
    """1 parameter use this list: LOWS FREQ

    On Cory Wong D.I. Funk Console.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N225_HZ = 0    # '225 Hz'
    N150_HZ = 1    # '150 Hz'


class Mid(IntEnum):
    """3 parameters use this list: BRIGHT, MID, PREAMP

    On Dumbbell ODS.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    OFF = 0
    BOOST = 1


class MidsFreq(IntEnum):
    """1 parameter use this list: MIDS FREQ

    On Cory Wong D.I. Funk Console.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N900_HZ = 0    # '900 Hz'
    N600_HZ = 1    # '600 Hz'


class MinivoicerMidiCh(IntEnum):
    """1 parameter use this list: MIDI CH

    On Minivoicer.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N5 = 4    # '5'
    N6 = 5    # '6'
    N7 = 6    # '7'
    N8 = 7    # '8'
    N9 = 8    # '9'
    N10 = 9    # '10'
    N11 = 10    # '11'
    N12 = 11    # '12'
    N13 = 12    # '13'
    N14 = 13    # '14'
    N15 = 14    # '15'
    N16 = 15    # '16'
    OMNI = 16


class MinivoicerMode(IntEnum):
    """2 parameters use this list: MODE

    On Minivoicer, Pitch Correction.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MAJOR = 0
    MINOR = 1
    CHROM = 2


class MinivoicerRoot(IntEnum):
    """2 parameters use this list: ROOT

    On Minivoicer, Pitch Correction.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    A = 0
    A_1 = 1    # 'A#'
    B = 2
    C = 3
    C_4 = 4    # 'C#'
    D = 5
    D_6 = 6    # 'D#'
    E = 7
    F = 8
    F_9 = 9    # 'F#'
    G = 10
    G_11 = 11    # 'G#'


class MixLaw(IntEnum):
    """6 parameters use this list: MIX LAW

    On 6 models, among them Cory Wong The Wash, Default Reverb, Gojira REV.

    NOT DRAWN by the unit, so these words cannot be held
    against a screen. Looked for on Gojira REV's MIX LAW and not
    found on any page of the block (2026-09-14). This is
    an observation, not the catalog's ``hidden`` flag - a
    list marked hidden IS drawn on a Mono Synth.
    """

    NOLLY = 0    # screen: None; catalog: 'nolly'
    NOLLYSKEWED = 1
    NOLLYSKEWEDPLUG = 2


class ModSource(IntEnum):
    """1 parameter use this list: MOD SOURCE

    On Micro Processor (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LFO = 0
    LFO_STEREO = 1    # 'LFO Stereo'
    PLUS_ENVELOPE = 2    # '+Envelope'
    MINUS_ENVELOPE = 3    # '-Envelope'


class MonoSynthMidiCh(IntEnum):
    """1 parameter use this list: MIDI CH.

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    OFF = 0
    N1 = 1    # '1'
    N2 = 2    # '2'
    N3 = 3    # '3'
    N4 = 4    # '4'
    N5 = 5    # '5'
    N6 = 6    # '6'
    N7 = 7    # '7'
    N8 = 8    # '8'
    N9 = 9    # '9'
    N10 = 10    # '10'
    N11 = 11    # '11'
    N12 = 12    # '12'
    N13 = 13    # '13'
    N14 = 14    # '14'
    N15 = 15    # '15'
    N16 = 16    # '16'
    OMNI = 17


class MonoSynthRoot(IntEnum):
    """1 parameter use this list: ROOT

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    OFF = 0
    A = 1
    A_2 = 2    # 'A#'
    B = 3
    C = 4
    C_5 = 5    # 'C#'
    D = 6
    D_7 = 7    # 'D#'
    E = 8
    F = 9
    F_10 = 10    # 'F#'
    G = 11
    G_12 = 12    # 'G#'


class MulSource(IntEnum):
    """1 parameter use this list: MUL. SOURCE

    On Phase-Locked Loop.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    UNISON = 0
    MINUS_1_OCTAVE = 1    # '-1 Octave'
    MINUS_2_OCTAVES = 2    # '-2 Octaves'


class Multiplier(IntEnum):
    """1 parameter use this list: MULTIPLIER

    On Phase-Locked Loop.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    X1 = 0
    X2 = 1
    X3 = 2
    X4 = 3
    X5 = 4
    X6 = 5
    X7 = 6
    X8 = 7


class MxPhase95Mode(IntEnum):
    """1 parameter use this list: MODE

    On MX Phase 95.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    BLOCK = 0
    SCRIPT = 1


class MxPhase95Type(IntEnum):
    """1 parameter use this list: TYPE

    On MX Phase 95.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N90 = 0    # '90'
    N45 = 1    # '45'


class NollyCompressorAttack(IntEnum):
    """1 parameter use this list: ATTACK

    On Nolly Compressor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SMOOTH = 0
    SNAPPY = 1


class Notelength(IntEnum):
    """1 parameter use this list: NOTELENGTH

    On TempoControl.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    QUARTER = 0
    EIGHTH = 1
    TRIPLET = 2
    SIXTEENTH = 3


class Octave(IntEnum):
    """1 parameter use this list: OCTAVE

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MINUS_2 = 0    # '-2'
    MINUS_1 = 1    # '-1'
    N0 = 2    # '0'
    N1 = 3    # '1'
    N2 = 4    # '2'


class OnOff(IntEnum):
    """1 parameter use this list: ON / OFF

    On Freeze.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    RELEASE = 0
    FREEZE = 1


class Osc1Wave(IntEnum):
    """2 parameters use this list: OSC1 WAVE, OSC2 WAVE

    On Mono Synth.

    Audited against the unit's screen 2026-09-14: all 7 positions read.
    The screen SPELLS 0, 1, 2, 3, 4 differently; its word is beside the member.
    The catalog is WRONG at 5, 6 - not a spelling, a different thing. The member name follows
    the screen, and naming these by the catalog's string is refused.
    """

    SINE = 0    # screen: 'SIN'; catalog: 'Sine'
    TRIANG = 1    # screen: 'TRI'; catalog: 'Triang'
    SAWTOOTH = 2    # screen: 'SAW'; catalog: 'Sawtooth'
    SQUARE = 3    # screen: 'SQR'; catalog: 'Square'
    PULSE = 4    # screen: 'PUL'; catalog: 'Pulse'
    WHITE_NS = 5    # screen: 'WHT'; catalog: 'Pink NS'
    PINK_NS = 6    # screen: 'PNK'; catalog: 'White NS'


class OutMode(IntEnum):
    """1 parameter use this list: OUT MODE

    On Chief CE2W (M).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MONO = 0
    WET_DRY = 1    # 'Wet/Dry'


class Peak(IntEnum):
    """1 parameter use this list: PEAK

    On Obsessive Drive.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LP = 0
    HP = 1


class Pickup(IntEnum):
    """1 parameter use this list: PICKUP

    On Facial Fuzz.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    HB = 0
    SINGLE = 1


class PliniChorusMode(IntEnum):
    """1 parameter use this list: MODE

    On Plini Chorus.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SPATIAL = 0
    VINTAGE = 1


class PliniDriveMode(IntEnum):
    """1 parameter use this list: MODE

    On Plini Drive.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    FZ = 0
    OD = 1


class PreRoll(IntEnum):
    """1 parameter use this list: PRE ROLL

    On Looper X.

    Audited against the unit's screen 2026-09-14: all 4 positions read.
    """

    OFF = 0
    N1_BAR = 1    # '1 BAR'
    N2_BARS = 2    # '2 BARS'
    N4_BARS = 3    # '4 BARS'


class PunchMode(IntEnum):
    """3 parameters use this list: OVERDUB MODE, PUNCH MODE, RECORD MODE

    On Looper X.

    Audited against the unit's screen 2026-09-14: all 2 positions read.
    """

    MOMENTARY = 0
    TOGGLE = 1


class Quality(IntEnum):
    """4 parameters use this list: QUALITY

    On 4 models, among them Analog Delay (M), Analog Delay (ST), Slapback Delay (M).

    NOT DRAWN by the unit, so these words cannot be held
    against a screen. Looked for on Slapback Delay (M)'s QUALITY and not
    found on any page of the block (2026-09-14). This is
    an observation, not the catalog's ``hidden`` flag - a
    list marked hidden IS drawn on a Mono Synth.
    """

    N0 = 0    # screen: None; catalog: '0'
    N1 = 1    # '1'
    N2 = 2    # '2'
    N3 = 3    # '3'


class Quantize(IntEnum):
    """1 parameter use this list: QUANTIZE

    On Looper X.

    Audited against the unit's screen 2026-09-14: all 10 positions read.
    """

    OFF = 0
    N1_BEAT = 1    # '1 Beat'
    N2_BEATS = 2    # '2 Beats'
    N3_BEATS = 3    # '3 Beats'
    N4_BEATS = 4    # '4 Beats'
    N5_BEATS = 5    # '5 Beats'
    N6_BEATS = 6    # '6 Beats'
    N7_BEATS = 7    # '7 Beats'
    N8_BEATS = 8    # '8 Beats'
    N16_BEATS = 9    # '16 Beats'


class Ratio3(IntEnum):
    """6 parameters use this list: RATIO

    On 6 models, among them Nolly Compressor, Plini Comp, SLO-100® Compressor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N2 = 0    # '2'
    N4 = 1    # '4'
    N10 = 2    # '10'


class RecLength(IntEnum):
    """1 parameter use this list: REC. LENGTH

    On Looper X.

    Audited against the unit's screen 2026-09-14: all 33 positions read.
    """

    OFF = 0
    N1_BAR = 1    # '1 BAR'
    N2_BARS = 2    # '2 BARS'
    N3_BARS = 3    # '3 BARS'
    N4_BARS = 4    # '4 BARS'
    N5_BARS = 5    # '5 BARS'
    N6_BARS = 6    # '6 BARS'
    N7_BARS = 7    # '7 BARS'
    N8_BARS = 8    # '8 BARS'
    N9_BARS = 9    # '9 BARS'
    N10_BARS = 10    # '10 BARS'
    N11_BARS = 11    # '11 BARS'
    N12_BARS = 12    # '12 BARS'
    N13_BARS = 13    # '13 BARS'
    N14_BARS = 14    # '14 BARS'
    N15_BARS = 15    # '15 BARS'
    N16_BARS = 16    # '16 BARS'
    N17_BARS = 17    # '17 BARS'
    N18_BARS = 18    # '18 BARS'
    N19_BARS = 19    # '19 BARS'
    N20_BARS = 20    # '20 BARS'
    N21_BARS = 21    # '21 BARS'
    N22_BARS = 22    # '22 BARS'
    N23_BARS = 23    # '23 BARS'
    N24_BARS = 24    # '24 BARS'
    N25_BARS = 25    # '25 BARS'
    N26_BARS = 26    # '26 BARS'
    N27_BARS = 27    # '27 BARS'
    N28_BARS = 28    # '28 BARS'
    N29_BARS = 29    # '29 BARS'
    N30_BARS = 30    # '30 BARS'
    N31_BARS = 31    # '31 BARS'
    N32_BARS = 32    # '32 BARS'


class RedDriveMode(IntEnum):
    """2 parameters use this list: INPUT, MODE

    On Fortin® Nameless, Red Drive.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LOW = 0
    HIGH = 1


class Resonance(IntEnum):
    """1 parameter use this list: RESONANCE

    On Flanger Engine.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    FULL = 0
    HOLLOW = 1
    RICH = 2
    INTENSE = 3


class Routing(IntEnum):
    """1 parameter use this list: ROUTING

    On TempoControl.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MULTI = 0
    HP = 1
    OUT_1_2 = 2    # 'OUT 1/2'
    OUT_3_4 = 3    # 'OUT 3/4'
    SEND_1_2 = 4    # 'SEND 1/2'


class RoutingMode(IntEnum):
    """1 parameter use this list: ROUTING MODE

    On Looper X.

    Audited against the unit's screen 2026-09-14: all 14 positions read.
    """

    GRID = 0
    IN_1 = 1    # 'In 1'
    IN_2 = 2    # 'In 2'
    RET_1 = 3    # 'Ret 1'
    RET_2 = 4    # 'Ret 2'
    IN_1_2 = 5    # 'In 1/2'
    RET_1_2 = 6    # 'Ret 1/2'
    OUT1 = 7
    OUT2 = 8
    OUT3 = 9
    OUT4 = 10
    OUT1_2 = 11    # 'Out1/2'
    OUT3_4 = 12    # 'Out3/4'
    MULTI = 13


class Scale(IntEnum):
    """1 parameter use this list: SCALE

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MAJOR = 0
    MINOR = 1


class Size(IntEnum):
    """40 parameters use this list: SIZE

    On 40 models, among them Ambience, Cory Wong Cab 1 (M), Cory Wong Cab 1 (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SMALL = 0
    MED = 1
    LARGE = 2


class SlapbackDelayMSyncNote(IntEnum):
    """2 parameters use this list: SYNC NOTE

    On Slapback Delay (M), Slapback Delay (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1_64T = 0    # '1/64T'
    N1_64 = 1    # '1/64'
    N1_32T = 2    # '1/32T'
    N1_64D = 3    # '1/64D'
    N1_32 = 4    # '1/32'
    N1_16T = 5    # '1/16T'
    N1_32D = 6    # '1/32D'
    N1_16 = 7    # '1/16'
    N1_8T = 8    # '1/8T'
    N1_16D = 9    # '1/16D'
    N1_8 = 10    # '1/8'


class Slope(IntEnum):
    """1 parameter use this list: SLOPE

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N6DB_OCT = 0    # '6dB/Oct'
    N12DB_OCT = 1    # '12dB/Oct'
    N18DB_OCT = 2    # '18dB/Oct'
    N24DB_OCT = 3    # '24dB/Oct'


class SoldanoSlo100Channel(IntEnum):
    """1 parameter use this list: CHANNEL

    On Soldano SLO-100®.

    NOT DRAWN by the unit, so these words cannot be held
    against a screen. Looked for on Soldano SLO-100®'s CHANNEL and not
    found on any page of the block (2026-09-14). This is
    an observation, not the catalog's ``hidden`` flag - a
    list marked hidden IS drawn on a Mono Synth.
    """

    CLEAN = 0    # screen: None; catalog: 'Clean'
    CRUNCH = 1
    LEAD = 2


class Sound(IntEnum):
    """1 parameter use this list: SOUND

    On TempoControl.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    BLIP = 0
    BLOCK = 1
    COWBELL = 2
    DIGITAL = 3
    DRUM_KIT = 4    # 'DRUM KIT'
    SOFT_KIT = 5    # 'SOFT KIT'


class Speed(IntEnum):
    """2 parameters use this list: ATTACK, SPEED

    On Rotary, SLO-100® Compressor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SLOW = 0
    FAST = 1


class SplitterMode(IntEnum):
    """2 parameters use this list: MODE

    On Splitter, Splitter Crossover.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    REGULAR = 0
    INVERT = 1


class SplitterType(IntEnum):
    """1 parameter use this list: TYPE

    On Splitter.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    BALANCE = 0
    A_B = 1    # 'A/B'
    CROSSOVER = 2


class Start(IntEnum):
    """2 parameters use this list: METRONOME MUTE, START

    On Looper X, TempoControl.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MUTE = 0
    UNMUTE = 1


class Stereo(IntEnum):
    """4 parameters use this list: STEREO

    On 4 models, among them Splitter, Splitter AB, Splitter Balance.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NORMAL = 0
    SPLIT = 1


class StereoLink(IntEnum):
    """1 parameter use this list: STEREO LINK

    On Phase Doctor.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    UNLINKED = 0
    LINKED = 1


class SyncNote11(IntEnum):
    """5 parameters use this list: CHR NOTE, SYNC NOTE

    On 5 models, among them Chief DC2W PCOM, Chorus 229T, Cory Wong The 80s.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1_8 = 0    # '1/8'
    N1_4T = 1    # '1/4T'
    N1_8D = 2    # '1/8D'
    N1_4 = 3    # '1/4'
    N1_2T = 4    # '1/2T'
    N1_4D = 5    # '1/4D'
    N1_2 = 6    # '1/2'
    N1_1T = 7    # '1/1T'
    N1_2D = 8    # '1/2D'
    N1_1 = 9    # '1/1'
    N1_1D = 10    # '1/1D'


class SyncNote14(IntEnum):
    """9 parameters use this list: SYNC NOTE

    On 9 models, among them Chief CE2W (M), Chief CE2W (ST), Dream Chorus (M).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1_16 = 0    # '1/16'
    N1_8T = 1    # '1/8T'
    N1_16D = 2    # '1/16D'
    N1_8 = 3    # '1/8'
    N1_4T = 4    # '1/4T'
    N1_8D = 5    # '1/8D'
    N1_4 = 6    # '1/4'
    N1_2T = 7    # '1/2T'
    N1_4D = 8    # '1/4D'
    N1_2 = 9    # '1/2'
    N1_1T = 10    # '1/1T'
    N1_2D = 11    # '1/2D'
    N1_1 = 12    # '1/1'
    N1_1D = 13    # '1/1D'


class SyncNote17(IntEnum):
    """14 parameters use this list: FAST NOTE, SLOW NOTE, SYNC NOTE

    On 12 models, among them Chorus Engine, Digital Flanger, Flanger Engine.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1_32 = 0    # '1/32'
    N1_16T = 1    # '1/16T'
    N1_32D = 2    # '1/32D'
    N1_16 = 3    # '1/16'
    N1_8T = 4    # '1/8T'
    N1_16D = 5    # '1/16D'
    N1_8 = 6    # '1/8'
    N1_4T = 7    # '1/4T'
    N1_8D = 8    # '1/8D'
    N1_4 = 9    # '1/4'
    N1_2T = 10    # '1/2T'
    N1_4D = 11    # '1/4D'
    N1_2 = 12    # '1/2'
    N1_1T = 13    # '1/1T'
    N1_2D = 14    # '1/2D'
    N1_1 = 15    # '1/1'
    N1_1D = 16    # '1/1D'


class SyncNote21(IntEnum):
    """28 parameters use this list: SYNC NOTE, SYNC NOTE A, SYNC NOTE B, SYNC NOTE L, SYNC NOTE R

    On 24 models, among them Circular Delay, Cory Wong Delay-y-y, Digital Delay (M).

    Audited against the unit's screen 2026-09-14: all 21 positions read.
    """

    N1_64T = 0    # '1/64T'
    N1_64 = 1    # '1/64'
    N1_32T = 2    # '1/32T'
    N1_64D = 3    # '1/64D'
    N1_32 = 4    # '1/32'
    N1_16T = 5    # '1/16T'
    N1_32D = 6    # '1/32D'
    N1_16 = 7    # '1/16'
    N1_8T = 8    # '1/8T'
    N1_16D = 9    # '1/16D'
    N1_8 = 10    # '1/8'
    N1_4T = 11    # '1/4T'
    N1_8D = 12    # '1/8D'
    N1_4 = 13    # '1/4'
    N1_2T = 14    # '1/2T'
    N1_4D = 15    # '1/4D'
    N1_2 = 16    # '1/2'
    N1_1T = 17    # '1/1T'
    N1_2D = 18    # '1/2D'
    N1_1 = 19    # '1/1'
    N1_1D = 20    # '1/1D'


class SyncOn(IntEnum):
    """1 parameter use this list: SYNC ON

    On Harmonic Tremolo.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    LOWS = 0
    HIGHS = 1


class TankType(IntEnum):
    """2 parameters use this list: TANK TYPE

    On Spring Reverb Engine (M), Spring Reverb Engine (ST).

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    VINTAGE = 0
    SHORT = 1
    MID = 2
    LONG = 3


class TapPreset(IntEnum):
    """1 parameter use this list: TAP PRESET

    On Circular Delay.

    Audited against the unit's screen 2026-09-14: all 9 positions read.
    """

    N1 = 0    # '1'
    N2 = 1    # '2'
    N3 = 2    # '3'
    N4 = 3    # '4'
    N4_ALT = 4    # '4 Alt'
    N5 = 5    # '5'
    N5_ALT = 6    # '5 Alt'
    N6 = 7    # '6'
    N6_ALT = 8    # '6 Alt'


class TempocontrolType(IntEnum):
    """1 parameter use this list: TYPE

    On TempoControl.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    PRESET = 0
    GLOBAL_ = 1    # 'Global'


class TimeSignature(IntEnum):
    """1 parameter use this list: TIME SIGNATURE

    On TempoControl.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N2_4 = 0    # '2/4'
    N3_4 = 1    # '3/4'
    N4_4 = 2    # '4/4'
    N5_4 = 3    # '5/4'
    N6_4 = 4    # '6/4'
    N7_4 = 5    # '7/4'
    N8_4 = 6    # '8/4'
    N9_4 = 7    # '9/4'
    N10_4 = 8    # '10/4'
    N11_4 = 9    # '11/4'
    N12_4 = 10    # '12/4'
    N13_4 = 11    # '13/4'
    N3_8 = 12    # '3/8'
    N6_8 = 13    # '6/8'
    N9_8 = 14    # '9/8'
    N12_8 = 15    # '12/8'
    N5_8_3_2 = 16    # '5/8 (3+2)'
    N5_8_2_3 = 17    # '5/8 (2+3)'
    N7_8_3_2_2 = 18    # '7/8 (3+2+2)'
    N7_8_2_3_2 = 19    # '7/8 (2+3+2)'
    N7_8_2_2_3 = 20    # '7/8 (2+2+3)'


class TremoloWaveform(IntEnum):
    """2 parameters use this list: WAVEFORM

    On Harmonic Tremolo, Tremolo.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    SINE = 0
    TRIANGLE = 1
    SQUARE = 2
    SAW_UP = 3    # 'Saw Up'
    SAW_DN = 4    # 'Saw Dn'


class TrigDirection(IntEnum):
    """1 parameter use this list: TRIG DIRECTION

    On Love Meat.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    DOWN = 0
    UP = 1


class TriggerMode(IntEnum):
    """1 parameter use this list: TRIGGER MODE

    On Love Meat.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    OFF = 0
    FULL = 1
    N1_2 = 2    # '1/2'


class Tube(IntEnum):
    """2 parameters use this list: TUBE

    On Victor Squid Ch1, Victor Squid Ch2.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N6L6 = 0    # '6L6'
    EL34 = 1


class UnisonSource(IntEnum):
    """1 parameter use this list: UNISON SOURCE

    On Mono Synth.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    OFF = 0
    OSC_1 = 1    # 'OSC 1'
    OSC_2 = 2    # 'OSC 2'
    OSC_1_2 = 3    # 'OSC 1 + 2'


class UsDlx64VintageMode(IntEnum):
    """2 parameters use this list: MODE

    On US DLX 64 Vintage, US DLX 65 Reissue.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    NORMAL = 0
    VIBRATO = 1
    VIBRATO_BRIGHT_OFF = 2    # 'Vibrato Bright Off'


class V1Inter(IntEnum):
    """2 parameters use this list: V1 INTER, V2 INTER

    On Minivoicer.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    MINUS_15TH = 0    # '-15th'
    MINUS_14TH = 1    # '-14th'
    MINUS_13TH = 2    # '-13th'
    MINUS_12TH = 3    # '-12th'
    MINUS_11TH = 4    # '-11th'
    MINUS_10TH = 5    # '-10th'
    MINUS_9TH = 6    # '-9th'
    MINUS_8TH = 7    # '-8th'
    MINUS_7TH = 8    # '-7th'
    MINUS_6TH = 9    # '-6th'
    MINUS_5TH = 10    # '-5th'
    MINUS_4TH = 11    # '-4th'
    MINUS_3RD = 12    # '-3rd'
    MINUS_2ND = 13    # '-2nd'
    ROOT = 14
    N2ND = 15    # '2nd'
    N3RD = 16    # '3rd'
    N4TH = 17    # '4th'
    N5TH = 18    # '5th'
    N6TH = 19    # '6th'
    N7TH = 20    # '7th'
    N8TH = 21    # '8th'
    N9TH = 22    # '9th'
    N10TH = 23    # '10th'
    N11TH = 24    # '11th'
    N12TH = 25    # '12th'
    N13TH = 26    # '13th'
    N14TH = 27    # '14th'
    N15TH = 28    # '15th'


class VibNote(IntEnum):
    """2 parameters use this list: VIB NOTE

    On Cory Wong The 80s, Vintage Chorus.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    N1_32 = 0    # '1/32'
    N1_16T = 1    # '1/16T'
    N1_32D = 2    # '1/32D'
    N1_16 = 3    # '1/16'
    N1_8T = 4    # '1/8T'
    N1_16D = 5    # '1/16D'
    N1_8 = 6    # '1/8'
    N1_4T = 7    # '1/4T'
    N1_8D = 8    # '1/8D'


class VintageChorusMode(IntEnum):
    """2 parameters use this list: MODE

    On Cory Wong The 80s, Vintage Chorus.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    CHORUS = 0
    VIBRATO = 1


class VoiceMode(IntEnum):
    """1 parameter use this list: VOICE MODE

    On Chorus Engine.

    NOT audited against the screen. These names are the
    catalog's ``stepNames``, which is not known to be the
    wording the unit draws.
    """

    FULL = 0
    THICK = 1
    OPEN = 2
    BROAD = 3


#: Each enum's options as the DEVICE spells them, in wire order.
#:
#: The member names above are ours - mangled to be valid Python, and
#: corrected where the device has a typo. These are the strings the
#: unit actually uses, which is what a dynamic list matches against.
OPTION_LABELS = {
    Adjust: ('Bypass', '90°', '180°'),
    AnalogDelayMSyncNote: ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1'),
    ArpPattern: ('Up', 'Down', 'Up & Down', 'Down & Up', 'Random'),
    BitDepth: ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'),
    Boost: ('HOT', 'COOL'),
    Bright: ('Normal', 'Bright 1', 'Bright 2'),
    Center: ('Lo Freq', 'Hi Freq'),
    ChannelNormal: ('Normal', 'OD'),
    ChiefCe2wMType: ('CE2-C', 'CE1-C', 'CE1-V'),
    ChiefDc2wMMode: ('1', '2', '3', '4', '1+2', '1+3', '1+4', '2+3', '2+4', '3+4'),
    ChiefDc2wMType: ('S', 'SDD-320'),
    Color: ('Natural', 'Warm', 'Dark', 'Bright', 'Sparkle', 'Dusty', 'Spiky', 'Twangy'),
    CoryWongDIFunkConsoleAttack: ('Fast', 'Slow'),
    CoryWongDelayYYMode: ('Single', 'Dual'),
    Crunch: ('Clean', 'Crunch'),
    Curve: ('Linear', 'Log'),
    DCellHisbertCh2Mode: ('-', '+'),
    Decay: ('Fast', 'Smooth'),
    DigitalFlangerPolarity: ('Neg', 'Pos'),
    DivSource: ('Unison', 'Multiplier'),
    Divider: ('2', '3', '4', '5', '6', '7', '8'),
    DreamChorusMMode: ('CHO1', 'CHO2'),
    DriveType: ('Soft', 'Edgy', 'Hard', 'Off'),
    DualChorusMode: ('Chorus', 'Vibe'),
    DumbbellOdsChannel: ('Clean', 'OD'),
    DumbbellOdsEq: ('Jazz', 'Rock'),
    DuplicateMode: ('Free', 'Sync'),
    DynMode2: ('Duck', 'Gate'),
    DynMode3: ('Off', 'Duck', 'Gate'),
    Eq3: ('Normal', 'Thick', 'Thicker'),
    FeedbackMode: ('Reverse', 'Flip'),
    Filter: ('4-POLE', '2-POLE'),
    FilterCutoff: ('Low', 'A', 'B', 'High'),
    FilterType: ('Lowpass', 'Bandpass', 'Highpass'),
    FlangerEngineWaveform: ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn', 'rndSmooth', 'rndStep'),
    Focus: ('ON', 'OFF'),
    Frequency: ('1', '2', '3', '4', '5'),
    GainPolarity: ('Normal', 'Inverted'),
    GojiraWowMode: ('Blade 2', 'Blade 1', 'FATSO'),
    HighsFreq: ('4 kHz', '2.5 kHz'),
    HpfSlope: ('Flat', '-6', '-12', '-18', '-24', '-30', '-36', '-42', '-48'),
    Input: ('Low', 'High'),
    Instrument: ('Guitar', 'Bass'),
    Invert: ('Noral', 'Inverted'),
    Legendary87MRatio: ('4', '8', '12', '20', 'All'),
    LowsFreq: ('225 Hz', '150 Hz'),
    Mid: ('Off', 'Boost'),
    MidsFreq: ('900 Hz', '600 Hz'),
    MinivoicerMidiCh: ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'),
    MinivoicerMode: ('Major', 'Minor', 'Chrom'),
    MinivoicerRoot: ('A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'),
    MixLaw: ('nolly', 'nollySkewed', 'nollySkewedPlug'),
    ModSource: ('LFO', 'LFO Stereo', '+Envelope', '-Envelope'),
    MonoSynthMidiCh: ('Off', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'),
    MonoSynthRoot: ('OFF', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'),
    MulSource: ('Unison', '-1 Octave', '-2 Octaves'),
    Multiplier: ('x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'),
    MxPhase95Mode: ('Block', 'Script'),
    MxPhase95Type: ('90', '45'),
    NollyCompressorAttack: ('Smooth', 'Snappy'),
    Notelength: ('QUARTER', 'EIGHTH', 'TRIPLET', 'SIXTEENTH'),
    Octave: ('-2', '-1', '0', '1', '2'),
    OnOff: ('RELEASE', 'FREEZE'),
    Osc1Wave: ('Sine', 'Triang', 'Sawtooth', 'Square', 'Pulse', 'Pink NS', 'White NS'),
    OutMode: ('Mono', 'Wet/Dry'),
    Peak: ('LP', 'HP'),
    Pickup: ('HB', 'SINGLE'),
    PliniChorusMode: ('Spatial', 'Vintage'),
    PliniDriveMode: ('FZ', 'OD'),
    PreRoll: ('OFF', '1 BAR', '2 BARS', '4 BARS'),
    PunchMode: ('Momentary', 'Toggle'),
    Quality: ('0', '1', '2', '3'),
    Quantize: ('OFF', '1 Beat', '2 Beats', '3 Beats', '4 Beats', '5 Beats', '6 Beats', '7 Beats', '8 Beats', '16 Beats'),
    Ratio3: ('2', '4', '10'),
    RecLength: ('OFF', '1 BAR', '2 BARS', '3 BARS', '4 BARS', '5 BARS', '6 BARS', '7 BARS', '8 BARS', '9 BARS', '10 BARS', '11 BARS', '12 BARS', '13 BARS', '14 BARS', '15 BARS', '16 BARS', '17 BARS', '18 BARS', '19 BARS', '20 BARS', '21 BARS', '22 BARS', '23 BARS', '24 BARS', '25 BARS', '26 BARS', '27 BARS', '28 BARS', '29 BARS', '30 BARS', '31 BARS', '32 BARS'),
    RedDriveMode: ('LOW', 'HIGH'),
    Resonance: ('Full', 'Hollow', 'Rich', 'Intense'),
    Routing: ('MULTI', 'HP', 'OUT 1/2', 'OUT 3/4', 'SEND 1/2'),
    RoutingMode: ('Grid', 'In 1', 'In 2', 'Ret 1', 'Ret 2', 'In 1/2', 'Ret 1/2', 'Out1', 'Out2', 'Out3', 'Out4', 'Out1/2', 'Out3/4', 'Multi'),
    Scale: ('Major', 'Minor'),
    Size: ('Small', 'Med', 'Large'),
    SlapbackDelayMSyncNote: ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8'),
    Slope: ('6dB/Oct', '12dB/Oct', '18dB/Oct', '24dB/Oct'),
    SoldanoSlo100Channel: ('Clean', 'Crunch', 'Lead'),
    Sound: ('BLIP', 'BLOCK', 'COWBELL', 'DIGITAL', 'DRUM KIT', 'SOFT KIT'),
    Speed: ('Slow', 'Fast'),
    SplitterMode: ('Regular', 'Invert'),
    SplitterType: ('Balance', 'A/B', 'Crossover'),
    Start: ('MUTE', 'UNMUTE'),
    Stereo: ('Normal', 'Split'),
    StereoLink: ('Unlinked', 'Linked'),
    SyncNote11: ('1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncNote14: ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncNote17: ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncNote21: ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'),
    SyncOn: ('Lows', 'Highs'),
    TankType: ('Vintage', 'Short', 'Mid', 'Long'),
    TapPreset: ('1', '2', '3', '4', '4 Alt', '5', '5 Alt', '6', '6 Alt'),
    TempocontrolType: ('Preset', 'Global'),
    TimeSignature: ('2/4', '3/4', '4/4', '5/4', '6/4', '7/4', '8/4', '9/4', '10/4', '11/4', '12/4', '13/4', '3/8', '6/8', '9/8', '12/8', '5/8 (3+2)', '5/8 (2+3)', '7/8 (3+2+2)', '7/8 (2+3+2)', '7/8 (2+2+3)'),
    TremoloWaveform: ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn'),
    TrigDirection: ('Down', 'Up'),
    TriggerMode: ('Off', 'Full', '1/2'),
    Tube: ('6L6', 'EL34'),
    UnisonSource: ('OFF', 'OSC 1', 'OSC 2', 'OSC 1 + 2'),
    UsDlx64VintageMode: ('Normal', 'Vibrato', 'Vibrato Bright Off'),
    V1Inter: ('-15th', '-14th', '-13th', '-12th', '-11th', '-10th', '-9th', '-8th', '-7th', '-6th', '-5th', '-4th', '-3rd', '-2nd', 'Root', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th'),
    VibNote: ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D'),
    VintageChorusMode: ('Chorus', 'Vibrato'),
    VoiceMode: ('Full', 'Thick', 'Open', 'Broad'),
}


#: Catalog names a driven reading showed to be WRONG about what the
#: position means, as ``{labels: {index: the catalog's name}}``.
#:
#: One entry: a Mono Synth's oscillator waveforms, where the catalog
#: has pink and white noise swapped. The strings stay in
#: ``OPTION_LABELS`` because the device publishes them, but naming
#: one of these in ``set_param_option`` is refused rather than
#: silently selecting the other noise.
OPTION_CONTESTED = {
    ('Sine', 'Triang', 'Sawtooth', 'Square', 'Pulse', 'Pink NS', 'White NS'): {5: 'Pink NS', 6: 'White NS'},
}


#: Whether anyone has held this list against the unit's SCREEN.
#:
#: Five answers, and every one of them is a recorded observation in
#: ``tests/fixtures/catalog/option_readings.json``:
#:
#: - ``"audited"`` - every position was read off the screen. It does
#:   NOT mean the words matched: a list can be audited AND
#:   disagree, which is the whole point of reading one. The enum's
#:   own docstring says which positions differ and how.
#: - ``"drawn"`` - every position was read, but the unit DRAWS them
#:   rather than naming them, so these words are still unchecked.
#: - ``"partial"`` - some positions were read and some were not.
#: - ``"absent"`` - somebody looked for the control and the unit
#:   does not draw it. NOT inferred from the catalog's ``hidden``
#:   flag, which marks a Mono Synth's ``OSC1 WAVE`` that is plainly
#:   on screen.
#: - ``None`` - the names are the catalog's and nobody has looked.
#:
#: Keyed by the LABELS rather than by the enum, because the two lists
#: that become a bool and the one published by hand have no enum and
#: are 13 parameters whose words still need
#: checking - the rest of those three lists have been read.
OPTION_AUDIT = {
    ('OFF', 'MUTE', 'DOWN', 'ON'): 'drawn',  # no enum
    ('OFF', 'ON'): 'audited',  # no enum
    ('Off', 'On'): 'audited',  # no enum
    ('Bypass', '90°', '180°'): None,  # Adjust
    ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1'): None,  # AnalogDelayMSyncNote
    ('Up', 'Down', 'Up & Down', 'Down & Up', 'Random'): None,  # ArpPattern
    ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'): None,  # BitDepth
    ('HOT', 'COOL'): None,  # Boost
    ('Normal', 'Bright 1', 'Bright 2'): None,  # Bright
    ('Lo Freq', 'Hi Freq'): None,  # Center
    ('Normal', 'OD'): None,  # ChannelNormal
    ('CE2-C', 'CE1-C', 'CE1-V'): None,  # ChiefCe2wMType
    ('1', '2', '3', '4', '1+2', '1+3', '1+4', '2+3', '2+4', '3+4'): None,  # ChiefDc2wMMode
    ('S', 'SDD-320'): None,  # ChiefDc2wMType
    ('Natural', 'Warm', 'Dark', 'Bright', 'Sparkle', 'Dusty', 'Spiky', 'Twangy'): None,  # Color
    ('Fast', 'Slow'): None,  # CoryWongDIFunkConsoleAttack
    ('Single', 'Dual'): None,  # CoryWongDelayYYMode
    ('Clean', 'Crunch'): None,  # Crunch
    ('Linear', 'Log'): 'audited',  # Curve
    ('-', '+'): None,  # DCellHisbertCh2Mode
    ('Fast', 'Smooth'): None,  # Decay
    ('Neg', 'Pos'): None,  # DigitalFlangerPolarity
    ('Unison', 'Multiplier'): None,  # DivSource
    ('2', '3', '4', '5', '6', '7', '8'): None,  # Divider
    ('CHO1', 'CHO2'): None,  # DreamChorusMMode
    ('Soft', 'Edgy', 'Hard', 'Off'): None,  # DriveType
    ('Chorus', 'Vibe'): None,  # DualChorusMode
    ('Clean', 'OD'): None,  # DumbbellOdsChannel
    ('Jazz', 'Rock'): None,  # DumbbellOdsEq
    ('Free', 'Sync'): 'audited',  # DuplicateMode
    ('Duck', 'Gate'): 'absent',  # DynMode2
    ('Off', 'Duck', 'Gate'): None,  # DynMode3
    ('Normal', 'Thick', 'Thicker'): None,  # Eq3
    ('Reverse', 'Flip'): None,  # FeedbackMode
    ('4-POLE', '2-POLE'): None,  # Filter
    ('Low', 'A', 'B', 'High'): None,  # FilterCutoff
    ('Lowpass', 'Bandpass', 'Highpass'): None,  # FilterType
    ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn', 'rndSmooth', 'rndStep'): 'audited',  # FlangerEngineWaveform
    ('ON', 'OFF'): None,  # Focus
    ('1', '2', '3', '4', '5'): None,  # Frequency
    ('Normal', 'Inverted'): None,  # GainPolarity
    ('Blade 2', 'Blade 1', 'FATSO'): None,  # GojiraWowMode
    ('4 kHz', '2.5 kHz'): None,  # HighsFreq
    ('Flat', '-6', '-12', '-18', '-24', '-30', '-36', '-42', '-48'): None,  # HpfSlope
    ('Low', 'High'): None,  # Input
    ('Guitar', 'Bass'): None,  # Instrument
    ('Noral', 'Inverted'): 'absent',  # Invert
    ('4', '8', '12', '20', 'All'): None,  # Legendary87MRatio
    ('225 Hz', '150 Hz'): None,  # LowsFreq
    ('Off', 'Boost'): None,  # Mid
    ('900 Hz', '600 Hz'): None,  # MidsFreq
    ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'): None,  # MinivoicerMidiCh
    ('Major', 'Minor', 'Chrom'): None,  # MinivoicerMode
    ('A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'): None,  # MinivoicerRoot
    ('nolly', 'nollySkewed', 'nollySkewedPlug'): 'absent',  # MixLaw
    ('LFO', 'LFO Stereo', '+Envelope', '-Envelope'): None,  # ModSource
    ('Off', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'): None,  # MonoSynthMidiCh
    ('OFF', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'): None,  # MonoSynthRoot
    ('Unison', '-1 Octave', '-2 Octaves'): None,  # MulSource
    ('x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'): None,  # Multiplier
    ('Block', 'Script'): None,  # MxPhase95Mode
    ('90', '45'): None,  # MxPhase95Type
    ('Smooth', 'Snappy'): None,  # NollyCompressorAttack
    ('QUARTER', 'EIGHTH', 'TRIPLET', 'SIXTEENTH'): None,  # Notelength
    ('-2', '-1', '0', '1', '2'): None,  # Octave
    ('RELEASE', 'FREEZE'): None,  # OnOff
    ('Sine', 'Triang', 'Sawtooth', 'Square', 'Pulse', 'Pink NS', 'White NS'): 'audited',  # Osc1Wave
    ('Mono', 'Wet/Dry'): None,  # OutMode
    ('LP', 'HP'): None,  # Peak
    ('HB', 'SINGLE'): None,  # Pickup
    ('Spatial', 'Vintage'): None,  # PliniChorusMode
    ('FZ', 'OD'): None,  # PliniDriveMode
    ('OFF', '1 BAR', '2 BARS', '4 BARS'): 'audited',  # PreRoll
    ('Momentary', 'Toggle'): 'audited',  # PunchMode
    ('0', '1', '2', '3'): 'absent',  # Quality
    ('OFF', '1 Beat', '2 Beats', '3 Beats', '4 Beats', '5 Beats', '6 Beats', '7 Beats', '8 Beats', '16 Beats'): 'audited',  # Quantize
    ('2', '4', '10'): None,  # Ratio3
    ('OFF', '1 BAR', '2 BARS', '3 BARS', '4 BARS', '5 BARS', '6 BARS', '7 BARS', '8 BARS', '9 BARS', '10 BARS', '11 BARS', '12 BARS', '13 BARS', '14 BARS', '15 BARS', '16 BARS', '17 BARS', '18 BARS', '19 BARS', '20 BARS', '21 BARS', '22 BARS', '23 BARS', '24 BARS', '25 BARS', '26 BARS', '27 BARS', '28 BARS', '29 BARS', '30 BARS', '31 BARS', '32 BARS'): 'audited',  # RecLength
    ('LOW', 'HIGH'): None,  # RedDriveMode
    ('Full', 'Hollow', 'Rich', 'Intense'): None,  # Resonance
    ('MULTI', 'HP', 'OUT 1/2', 'OUT 3/4', 'SEND 1/2'): None,  # Routing
    ('Grid', 'In 1', 'In 2', 'Ret 1', 'Ret 2', 'In 1/2', 'Ret 1/2', 'Out1', 'Out2', 'Out3', 'Out4', 'Out1/2', 'Out3/4', 'Multi'): 'audited',  # RoutingMode
    ('Major', 'Minor'): None,  # Scale
    ('Small', 'Med', 'Large'): None,  # Size
    ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8'): None,  # SlapbackDelayMSyncNote
    ('6dB/Oct', '12dB/Oct', '18dB/Oct', '24dB/Oct'): None,  # Slope
    ('Clean', 'Crunch', 'Lead'): 'absent',  # SoldanoSlo100Channel
    ('BLIP', 'BLOCK', 'COWBELL', 'DIGITAL', 'DRUM KIT', 'SOFT KIT'): None,  # Sound
    ('Slow', 'Fast'): None,  # Speed
    ('Regular', 'Invert'): None,  # SplitterMode
    ('Balance', 'A/B', 'Crossover'): None,  # SplitterType
    ('MUTE', 'UNMUTE'): None,  # Start
    ('Normal', 'Split'): None,  # Stereo
    ('Unlinked', 'Linked'): None,  # StereoLink
    ('1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): None,  # SyncNote11
    ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): None,  # SyncNote14
    ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): None,  # SyncNote17
    ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): 'audited',  # SyncNote21
    ('Lows', 'Highs'): None,  # SyncOn
    ('Vintage', 'Short', 'Mid', 'Long'): None,  # TankType
    ('1', '2', '3', '4', '4 Alt', '5', '5 Alt', '6', '6 Alt'): 'audited',  # TapPreset
    ('Preset', 'Global'): None,  # TempocontrolType
    ('2/4', '3/4', '4/4', '5/4', '6/4', '7/4', '8/4', '9/4', '10/4', '11/4', '12/4', '13/4', '3/8', '6/8', '9/8', '12/8', '5/8 (3+2)', '5/8 (2+3)', '7/8 (3+2+2)', '7/8 (2+3+2)', '7/8 (2+2+3)'): None,  # TimeSignature
    ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn'): None,  # TremoloWaveform
    ('Down', 'Up'): None,  # TrigDirection
    ('Off', 'Full', '1/2'): None,  # TriggerMode
    ('6L6', 'EL34'): None,  # Tube
    ('OFF', 'OSC 1', 'OSC 2', 'OSC 1 + 2'): None,  # UnisonSource
    ('Normal', 'Vibrato', 'Vibrato Bright Off'): None,  # UsDlx64VintageMode
    ('-15th', '-14th', '-13th', '-12th', '-11th', '-10th', '-9th', '-8th', '-7th', '-6th', '-5th', '-4th', '-3rd', '-2nd', 'Root', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th'): None,  # V1Inter
    ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D'): None,  # VibNote
    ('Chorus', 'Vibrato'): None,  # VintageChorusMode
    ('Full', 'Thick', 'Open', 'Broad'): None,  # VoiceMode
}


#: How many PARAMETERS each fixed list decides, as
#: ``{labels: count}``.
#:
#: Published beside ``OPTION_AUDIT`` because the two are read
#: together: a list nobody has looked at matters in proportion to
#: how many controls it governs, and the numbers were being quoted
#: in prose from one-off counts before this existed. Keyed by the
#: LABELS, like the audit, so the three lists with no enum are in
#: it too.
#:
#: Totals on this snapshot: 611
#: parameters across 113 lists, of which 218 across
#: 94 lists nobody has read. The work is long-tailed - the
#: five biggest unread lists cover 82 of those 218.
OPTION_USAGE = {
    ('OFF', 'MUTE', 'DOWN', 'ON'): 13,  # no enum
    ('OFF', 'ON'): 25,  # no enum
    ('Off', 'On'): 278,  # no enum
    ('Bypass', '90°', '180°'): 2,  # Adjust
    ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1'): 2,  # AnalogDelayMSyncNote
    ('Up', 'Down', 'Up & Down', 'Down & Up', 'Random'): 1,  # ArpPattern
    ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'): 2,  # BitDepth
    ('HOT', 'COOL'): 2,  # Boost
    ('Normal', 'Bright 1', 'Bright 2'): 1,  # Bright
    ('Lo Freq', 'Hi Freq'): 2,  # Center
    ('Normal', 'OD'): 1,  # ChannelNormal
    ('CE2-C', 'CE1-C', 'CE1-V'): 2,  # ChiefCe2wMType
    ('1', '2', '3', '4', '1+2', '1+3', '1+4', '2+3', '2+4', '3+4'): 2,  # ChiefDc2wMMode
    ('S', 'SDD-320'): 2,  # ChiefDc2wMType
    ('Natural', 'Warm', 'Dark', 'Bright', 'Sparkle', 'Dusty', 'Spiky', 'Twangy'): 1,  # Color
    ('Fast', 'Slow'): 1,  # CoryWongDIFunkConsoleAttack
    ('Single', 'Dual'): 1,  # CoryWongDelayYYMode
    ('Clean', 'Crunch'): 1,  # Crunch
    ('Linear', 'Log'): 1,  # Curve
    ('-', '+'): 1,  # DCellHisbertCh2Mode
    ('Fast', 'Smooth'): 1,  # Decay
    ('Neg', 'Pos'): 1,  # DigitalFlangerPolarity
    ('Unison', 'Multiplier'): 1,  # DivSource
    ('2', '3', '4', '5', '6', '7', '8'): 1,  # Divider
    ('CHO1', 'CHO2'): 2,  # DreamChorusMMode
    ('Soft', 'Edgy', 'Hard', 'Off'): 2,  # DriveType
    ('Chorus', 'Vibe'): 1,  # DualChorusMode
    ('Clean', 'OD'): 1,  # DumbbellOdsChannel
    ('Jazz', 'Rock'): 1,  # DumbbellOdsEq
    ('Free', 'Sync'): 1,  # DuplicateMode
    ('Duck', 'Gate'): 9,  # DynMode2
    ('Off', 'Duck', 'Gate'): 11,  # DynMode3
    ('Normal', 'Thick', 'Thicker'): 8,  # Eq3
    ('Reverse', 'Flip'): 2,  # FeedbackMode
    ('4-POLE', '2-POLE'): 1,  # Filter
    ('Low', 'A', 'B', 'High'): 1,  # FilterCutoff
    ('Lowpass', 'Bandpass', 'Highpass'): 1,  # FilterType
    ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn', 'rndSmooth', 'rndStep'): 1,  # FlangerEngineWaveform
    ('ON', 'OFF'): 2,  # Focus
    ('1', '2', '3', '4', '5'): 2,  # Frequency
    ('Normal', 'Inverted'): 3,  # GainPolarity
    ('Blade 2', 'Blade 1', 'FATSO'): 1,  # GojiraWowMode
    ('4 kHz', '2.5 kHz'): 1,  # HighsFreq
    ('Flat', '-6', '-12', '-18', '-24', '-30', '-36', '-42', '-48'): 2,  # HpfSlope
    ('Low', 'High'): 2,  # Input
    ('Guitar', 'Bass'): 1,  # Instrument
    ('Noral', 'Inverted'): 16,  # Invert
    ('4', '8', '12', '20', 'All'): 3,  # Legendary87MRatio
    ('225 Hz', '150 Hz'): 1,  # LowsFreq
    ('Off', 'Boost'): 3,  # Mid
    ('900 Hz', '600 Hz'): 1,  # MidsFreq
    ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'): 1,  # MinivoicerMidiCh
    ('Major', 'Minor', 'Chrom'): 2,  # MinivoicerMode
    ('A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'): 2,  # MinivoicerRoot
    ('nolly', 'nollySkewed', 'nollySkewedPlug'): 6,  # MixLaw
    ('LFO', 'LFO Stereo', '+Envelope', '-Envelope'): 1,  # ModSource
    ('Off', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', 'Omni'): 1,  # MonoSynthMidiCh
    ('OFF', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'): 1,  # MonoSynthRoot
    ('Unison', '-1 Octave', '-2 Octaves'): 1,  # MulSource
    ('x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'): 1,  # Multiplier
    ('Block', 'Script'): 1,  # MxPhase95Mode
    ('90', '45'): 1,  # MxPhase95Type
    ('Smooth', 'Snappy'): 1,  # NollyCompressorAttack
    ('QUARTER', 'EIGHTH', 'TRIPLET', 'SIXTEENTH'): 1,  # Notelength
    ('-2', '-1', '0', '1', '2'): 1,  # Octave
    ('RELEASE', 'FREEZE'): 1,  # OnOff
    ('Sine', 'Triang', 'Sawtooth', 'Square', 'Pulse', 'Pink NS', 'White NS'): 2,  # Osc1Wave
    ('Mono', 'Wet/Dry'): 1,  # OutMode
    ('LP', 'HP'): 1,  # Peak
    ('HB', 'SINGLE'): 1,  # Pickup
    ('Spatial', 'Vintage'): 1,  # PliniChorusMode
    ('FZ', 'OD'): 1,  # PliniDriveMode
    ('OFF', '1 BAR', '2 BARS', '4 BARS'): 1,  # PreRoll
    ('Momentary', 'Toggle'): 3,  # PunchMode
    ('0', '1', '2', '3'): 4,  # Quality
    ('OFF', '1 Beat', '2 Beats', '3 Beats', '4 Beats', '5 Beats', '6 Beats', '7 Beats', '8 Beats', '16 Beats'): 1,  # Quantize
    ('2', '4', '10'): 6,  # Ratio3
    ('OFF', '1 BAR', '2 BARS', '3 BARS', '4 BARS', '5 BARS', '6 BARS', '7 BARS', '8 BARS', '9 BARS', '10 BARS', '11 BARS', '12 BARS', '13 BARS', '14 BARS', '15 BARS', '16 BARS', '17 BARS', '18 BARS', '19 BARS', '20 BARS', '21 BARS', '22 BARS', '23 BARS', '24 BARS', '25 BARS', '26 BARS', '27 BARS', '28 BARS', '29 BARS', '30 BARS', '31 BARS', '32 BARS'): 1,  # RecLength
    ('LOW', 'HIGH'): 2,  # RedDriveMode
    ('Full', 'Hollow', 'Rich', 'Intense'): 1,  # Resonance
    ('MULTI', 'HP', 'OUT 1/2', 'OUT 3/4', 'SEND 1/2'): 1,  # Routing
    ('Grid', 'In 1', 'In 2', 'Ret 1', 'Ret 2', 'In 1/2', 'Ret 1/2', 'Out1', 'Out2', 'Out3', 'Out4', 'Out1/2', 'Out3/4', 'Multi'): 1,  # RoutingMode
    ('Major', 'Minor'): 1,  # Scale
    ('Small', 'Med', 'Large'): 40,  # Size
    ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8'): 2,  # SlapbackDelayMSyncNote
    ('6dB/Oct', '12dB/Oct', '18dB/Oct', '24dB/Oct'): 1,  # Slope
    ('Clean', 'Crunch', 'Lead'): 1,  # SoldanoSlo100Channel
    ('BLIP', 'BLOCK', 'COWBELL', 'DIGITAL', 'DRUM KIT', 'SOFT KIT'): 1,  # Sound
    ('Slow', 'Fast'): 2,  # Speed
    ('Regular', 'Invert'): 2,  # SplitterMode
    ('Balance', 'A/B', 'Crossover'): 1,  # SplitterType
    ('MUTE', 'UNMUTE'): 2,  # Start
    ('Normal', 'Split'): 4,  # Stereo
    ('Unlinked', 'Linked'): 1,  # StereoLink
    ('1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): 5,  # SyncNote11
    ('1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): 9,  # SyncNote14
    ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): 14,  # SyncNote17
    ('1/64T', '1/64', '1/32T', '1/64D', '1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D', '1/4', '1/2T', '1/4D', '1/2', '1/1T', '1/2D', '1/1', '1/1D'): 28,  # SyncNote21
    ('Lows', 'Highs'): 1,  # SyncOn
    ('Vintage', 'Short', 'Mid', 'Long'): 2,  # TankType
    ('1', '2', '3', '4', '4 Alt', '5', '5 Alt', '6', '6 Alt'): 1,  # TapPreset
    ('Preset', 'Global'): 1,  # TempocontrolType
    ('2/4', '3/4', '4/4', '5/4', '6/4', '7/4', '8/4', '9/4', '10/4', '11/4', '12/4', '13/4', '3/8', '6/8', '9/8', '12/8', '5/8 (3+2)', '5/8 (2+3)', '7/8 (3+2+2)', '7/8 (2+3+2)', '7/8 (2+2+3)'): 1,  # TimeSignature
    ('Sine', 'Triangle', 'Square', 'Saw Up', 'Saw Dn'): 2,  # TremoloWaveform
    ('Down', 'Up'): 1,  # TrigDirection
    ('Off', 'Full', '1/2'): 1,  # TriggerMode
    ('6L6', 'EL34'): 2,  # Tube
    ('OFF', 'OSC 1', 'OSC 2', 'OSC 1 + 2'): 1,  # UnisonSource
    ('Normal', 'Vibrato', 'Vibrato Bright Off'): 2,  # UsDlx64VintageMode
    ('-15th', '-14th', '-13th', '-12th', '-11th', '-10th', '-9th', '-8th', '-7th', '-6th', '-5th', '-4th', '-3rd', '-2nd', 'Root', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th'): 2,  # V1Inter
    ('1/32', '1/16T', '1/32D', '1/16', '1/8T', '1/16D', '1/8', '1/4T', '1/8D'): 2,  # VibNote
    ('Chorus', 'Vibrato'): 2,  # VintageChorusMode
    ('Full', 'Thick', 'Open', 'Broad'): 1,  # VoiceMode
}


__all__ = [
    "Adjust",
    "AnalogDelayMSyncNote",
    "ArpPattern",
    "BitDepth",
    "Boost",
    "Bright",
    "Center",
    "ChannelNormal",
    "ChiefCe2wMType",
    "ChiefDc2wMMode",
    "ChiefDc2wMType",
    "Color",
    "CoryWongDIFunkConsoleAttack",
    "CoryWongDelayYYMode",
    "Crunch",
    "Curve",
    "DCellHisbertCh2Mode",
    "Decay",
    "DigitalFlangerPolarity",
    "DivSource",
    "Divider",
    "DreamChorusMMode",
    "DriveType",
    "DualChorusMode",
    "DumbbellOdsChannel",
    "DumbbellOdsEq",
    "DuplicateMode",
    "DynMode2",
    "DynMode3",
    "Eq3",
    "FeedbackMode",
    "Filter",
    "FilterCutoff",
    "FilterType",
    "FlangerEngineWaveform",
    "Focus",
    "Frequency",
    "GainPolarity",
    "GojiraWowMode",
    "HighsFreq",
    "HpfSlope",
    "Input",
    "Instrument",
    "Invert",
    "Legendary87MRatio",
    "LowsFreq",
    "Mid",
    "MidsFreq",
    "MinivoicerMidiCh",
    "MinivoicerMode",
    "MinivoicerRoot",
    "MixLaw",
    "ModSource",
    "MonoSynthMidiCh",
    "MonoSynthRoot",
    "MulSource",
    "Multiplier",
    "MxPhase95Mode",
    "MxPhase95Type",
    "NollyCompressorAttack",
    "Notelength",
    "Octave",
    "OnOff",
    "Osc1Wave",
    "OutMode",
    "Peak",
    "Pickup",
    "PliniChorusMode",
    "PliniDriveMode",
    "PreRoll",
    "PunchMode",
    "Quality",
    "Quantize",
    "Ratio3",
    "RecLength",
    "RedDriveMode",
    "Resonance",
    "Routing",
    "RoutingMode",
    "Scale",
    "Size",
    "SlapbackDelayMSyncNote",
    "Slope",
    "SoldanoSlo100Channel",
    "Sound",
    "Speed",
    "SplitterMode",
    "SplitterType",
    "Start",
    "Stereo",
    "StereoLink",
    "SyncNote11",
    "SyncNote14",
    "SyncNote17",
    "SyncNote21",
    "SyncOn",
    "TankType",
    "TapPreset",
    "TempocontrolType",
    "TimeSignature",
    "TremoloWaveform",
    "TrigDirection",
    "TriggerMode",
    "Tube",
    "UnisonSource",
    "UsDlx64VintageMode",
    "V1Inter",
    "VibNote",
    "VintageChorusMode",
    "VoiceMode",
    "OPTION_LABELS",
    "OPTION_AUDIT",
    "OPTION_USAGE",
    "OPTION_CONTESTED",
]
