"""Parameter constants for the factory blocks every Quad Cortex has.

GENERATED by scripts/generate_params.py - do not edit by hand.

Each class is a model and each member a parameter's wire index, so a
member goes straight to :meth:`pyquadcortex.protocol.QuadCortex.set_param`::

    qc.set_param(LaneOutput(0), params.LaneOutputParam.VOLUME, real=-3.1)

These are ``IntEnum``, so a member IS its wire index and passing one
needs no catalog - which also makes it the cheapest route, since a
catalog is fetched from the device.

**Cabs share one layout.** The catalog lists two parameters for a cab -
its two mic selectors - while the wire carries 22. So a cab is CHOSEN by
its `models.*` id and DRIVEN through :class:`Cabsim`::

    qc.set_block(Block(0, 5, models.CabsimBassM.N212_DARKGLASS_NEO))
    qc.set_param(Block(0, 5), params.Cabsim.MIC_1_DISTANCE, real=3.0)

A name the device publishes twice is numbered by occurrence, and BOTH
occurrences are numbered. For a cab that repetition is a MICROPHONE and
for an IR Loader it is an IR slot; both are measured, not assumed.

Only FACTORY content is here, as in `models.py`. Resolve anything else
through ``qc.catalog``.
"""
from enum import IntEnum


# -- the containers a target addresses ----------------------------------------


class LaneOutputParam(IntEnum):
    """A row's Lane Output Control - `LaneOutput(row)`."""

    VOLUME = 0    # float dB
    PAN = 1    # float
    MUTE = 2    # switch
    SOLO = 3    # switch


class LaneInputParam(IntEnum):
    """A row's Input Gate Control - `LaneInput(row)`."""

    NOISE_REDUCTION = 0    # float %
    BYPASS = 1    # switch
    GAIN_REDUCTION = 2    # grMeter dB
    INPUT_GAIN = 3    # float dB


class MixerParam(IntEnum):
    """A row's Mixer - `Mixer(row)`."""

    LEVEL_A = 0    # float dB
    PAN_A = 1    # float
    LEVEL_B = 2    # float dB
    PAN_B = 3    # float
    PHASE = 4    # switch
    MIXER_LEVEL = 5    # float dB
    SPLIT_MODE = 6    # float


class SplitterParam(IntEnum):
    """A row's splitter - `Splitter(row)`."""

    TYPE = 0    # switch
    STEREO = 1    # switch
    BALANCE = 2    # float
    LEVEL_TO_A = 3    # float dB
    LEVEL_TO_B = 4    # float dB
    FREQUENCY = 5    # float Hz
    MODE = 6    # switch


class SplitterABParam(IntEnum):
    """The older two-parameter splitter view."""

    LEVEL_TO_A = 0    # float dB
    LEVEL_TO_B = 1    # float dB
    STEREO = 2    # switch


class TempoParam(IntEnum):
    """The preset's TempoControl - `Tempo()`."""

    TEMPO = 0    # float BPM
    TYPE = 1    # switch
    LED_LIGHT = 2    # switch
    VOLUME = 3    # float dB
    START = 4    # toggleButton
    PAN = 5    # float
    TIME_SIGNATURE = 6    # comboBox
    NOTELENGTH = 7    # comboBox
    SOUND = 8    # comboBox
    ROUTING = 9    # comboBox
    STEPSTATE0 = 10    # empty
    STEPSTATE1 = 11    # empty
    STEPSTATE2 = 12    # empty
    STEPSTATE3 = 13    # empty
    STEPSTATE4 = 14    # empty
    STEPSTATE5 = 15    # empty
    STEPSTATE6 = 16    # empty
    STEPSTATE7 = 17    # empty
    STEPSTATE8 = 18    # empty
    STEPSTATE9 = 19    # empty
    STEPSTATE10 = 20    # empty
    STEPSTATE11 = 21    # empty
    STEPSTATE12 = 22    # empty


# -- cabs: one layout, shared by every cab model ------------------------------


class Cabsim(IntEnum):
    """Every cab model's parameters. The catalog under-describes these.

    Measured on four cabs across all four categories: the wire carries
    22 parameters in the `Default Cabsim` layout regardless of which cab
    is loaded, or whether it is mono or stereo. `MIC_1_PAN` is labelled
    BALANCE on a stereo cab and PAN on a mono one - one wire index, two
    screen names.

    The mic-to-index mapping was confirmed against the unit's own
    editor. Index 21 exists on the wire, is absent from the catalog and
    reads 0.0 everywhere, so it is omitted rather than guessed at.
    """

    MIC_1_BYPASS = 0    # switch
    MIC_1_IR_SELECTOR = 1    # string
    MIC_1_LEVEL = 2    # float dB
    MIC_1_PAN = 3    # float
    MIC_1_DISTANCE = 4    # float
    MIC_1_POSITION = 5    # float
    MIC_1_PHI = 6    # switch
    MIC_1_GRID_MODE = 7    # switch
    MIC_2_BYPASS = 8    # switch
    MIC_2_IR_SELECTOR = 9    # string
    MIC_2_LEVEL = 10    # float dB
    MIC_2_PAN = 11    # float
    MIC_2_DISTANCE = 12    # float
    MIC_2_POSITION = 13    # float
    MIC_2_PHI = 14    # switch
    MIC_2_GRID_MODE = 15    # switch
    HPF = 16    # float Hz
    LPF = 17    # float Hz
    OUTPUT_VOLUME = 18    # float dB
    MIC_1_IR_NAME = 19    # string
    MIC_2_IR_NAME = 20    # string


# -- every other factory model -----------------------------------------------


class MythDrive(IntEnum):
    """Myth Drive (Guitar Overdrive)."""

    GAIN = 0    # float
    TREBLE = 1    # float
    LEVEL = 2    # float


class ObsessiveDrive(IntEnum):
    """Obsessive Drive (Guitar Overdrive)."""

    DRIVE = 0    # float
    PEAK = 1    # switch
    TONE = 2    # float
    VOLUME = 3    # float


class Od250(IntEnum):
    """OD250 (Guitar Overdrive)."""

    GAIN = 0    # float
    VOLUME = 1    # float


class RodentDrive(IntEnum):
    """Rodent Drive (Guitar Overdrive)."""

    DISTORTION = 0    # float
    FILTER = 1    # float
    VOLUME = 2    # float


class Exotic(IntEnum):
    """Exotic (Guitar Overdrive)."""

    GAIN = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    VOLUME = 3    # float


class FreemanBod(IntEnum):
    """Freeman BOD (Guitar Overdrive)."""

    GAIN = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    PRESENCE = 3    # float
    TIGHT = 4    # float
    TRIM = 5    # float
    VOLUME = 6    # float


class BritBlues(IntEnum):
    """Brit Blues (Guitar Overdrive)."""

    GAIN = 0    # float
    TONE = 1    # float
    VOLUME = 2    # float


class ChiefDs1(IntEnum):
    """Chief DS1 (Guitar Overdrive)."""

    DISTORTION = 0    # float
    TONE = 1    # float
    LEVEL = 2    # float


class BritGovernor(IntEnum):
    """Brit Governor (Guitar Overdrive)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    LEVEL = 4    # float


class ChiefMt(IntEnum):
    """Chief MT (Guitar Overdrive)."""

    DIST = 0    # float
    LOW = 1    # float
    MIDDLE = 2    # float
    MIDFREQ = 3    # float
    HIGH = 4    # float
    LEVEL = 5    # float


class ChiefOd1(IntEnum):
    """Chief OD1 (Guitar Overdrive)."""

    GAIN = 0    # float
    LEVEL = 1    # float


class ChiefSd1(IntEnum):
    """Chief SD1 (Guitar Overdrive)."""

    OVERDRIVE = 0    # float
    TONE = 1    # float
    LEVEL = 2    # float


class FuzzPi(IntEnum):
    """Fuzz Pi (Guitar Overdrive)."""

    SUSTAIN = 0    # float
    TONE = 1    # float
    VOLUME = 2    # float


class ChiefBd2(IntEnum):
    """Chief BD2 (Guitar Overdrive)."""

    GAIN = 0    # float
    TONE = 1    # float
    VOLUME = 2    # float


class RageBooster(IntEnum):
    """Rage Booster (Guitar Overdrive)."""

    VOLUME = 0    # float


class FacialFuzz(IntEnum):
    """Facial Fuzz (Guitar Overdrive)."""

    FUZZ = 0    # float
    VOLUME = 1    # float
    PICKUP = 2    # switch
    PICKUP_LEVEL = 3    # float


class ExoticZBoost(IntEnum):
    """Exotic Z Boost (Guitar Overdrive)."""

    GAIN = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    VOLUME = 3    # float


class RedDrive(IntEnum):
    """Red Drive (Guitar Overdrive)."""

    DRIVE = 0    # float
    TONE = 1    # float
    LEVEL = 2    # float
    MODE = 3    # switch


class VemuralRay(IntEnum):
    """Vemural Ray (Guitar Overdrive)."""

    GAIN = 0    # float
    TREBLE = 1    # float
    BASS = 2    # float
    LEVEL = 3    # float


class NoBellOd1(IntEnum):
    """No-Bell OD1 (Guitar Overdrive)."""

    DRIVE = 0    # float
    SPECTRUM = 1    # float
    LEVEL = 2    # float
    BASS_CUT = 3    # switch
    MUTE_TRIG = 4    # switch


class Green808(IntEnum):
    """Green 808 (Guitar Overdrive)."""

    OVERDRIVE = 0    # float
    TONE = 1    # float
    LEVEL = 2    # float


class Thunderpaw(IntEnum):
    """Thunderpaw (Guitar Overdrive)."""

    OUTPUT = 0    # float
    DISTORTION = 1    # float
    BASS = 2    # float
    TREBLE = 3    # float
    USE_GATE = 4    # switch


class Mk3SiliconFuzz(IntEnum):
    """MK3 Silicon Fuzz (Guitar Overdrive)."""

    ATTACK = 0    # float
    TONE = 1    # float
    LEVEL = 2    # float


class N81CreationsDrive(IntEnum):
    """81 Creations Drive (Guitar Overdrive)."""

    DRV = 0    # float %
    CUT = 1    # float %
    OUTPUT = 2    # float dB
    LEVEL = 3    # float %


class Brit2203(IntEnum):
    """Brit 2203 (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class Pv505Lead(IntEnum):
    """PV-505 Lead (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEPTH = 6    # float
    OUTPUT = 7    # float dB


class RolsJazzCh120(IntEnum):
    """Rols Jazz CH120 (Guitar Amplifier)."""

    BRIGHT = 0    # switch
    VOLUME = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    OUTPUT = 5    # float dB


class UkC30Normal(IntEnum):
    """UK C30 Normal (Guitar Amplifier)."""

    BRIGHT = 0    # switch
    VOLUME = 1    # float
    TONE_CUT = 2    # float
    OUTPUT = 3    # float dB


class UkC30Topboost(IntEnum):
    """UK C30 TopBoost (Guitar Amplifier)."""

    VOLUME = 0    # float
    BOOST = 1    # switch
    BASS = 2    # float
    TREBLE = 3    # float
    TONE_CUT = 4    # float
    OUTPUT = 5    # float dB


class CaDuoCh3Modern(IntEnum):
    """CA Duo Ch3 Modern (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class CaDuoCh3Raw(IntEnum):
    """CA Duo Ch3 Raw (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class CaDuoCh3Vintage(IntEnum):
    """CA Duo Ch3 Vintage (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class Freeman100Clean(IntEnum):
    """Freeman 100 Clean (Guitar Amplifier)."""

    BRIGHT = 0    # rotarySwitch
    BASS = 1    # float
    TREBLE = 2    # float
    VOLUME = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class Freeman100Rhythm(IntEnum):
    """Freeman 100 Rhythm (Guitar Amplifier)."""

    FAT = 0    # switch
    C45 = 1    # switch
    GAIN = 2    # float
    VOICE = 3    # switch
    SAT = 4    # switch
    BASS = 5    # float
    MID = 6    # float
    TREBLE = 7    # float
    MASTER = 8    # float
    PRESENCE = 9    # float
    OUTPUT = 10    # float dB


class BritTm45Normal(IntEnum):
    """Brit TM45 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class BritTm45Bright(IntEnum):
    """Brit TM45 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class BritTm45Patch(IntEnum):
    """Brit TM45 Patch (Guitar Amplifier)."""

    GAIN_1 = 0    # float
    GAIN_2 = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class Brit900Clean(IntEnum):
    """Brit 900 Clean (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class Brit900Lead(IntEnum):
    """Brit 900 Lead (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class WattD103Normal(IntEnum):
    """Watt D103 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class WattD103Bright(IntEnum):
    """Watt D103 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class BritPlexi50Bright(IntEnum):
    """Brit Plexi 50 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class BritPlexi50Patch(IntEnum):
    """Brit Plexi 50 Patch (Guitar Amplifier)."""

    GAIN_1 = 0    # float
    GAIN_2 = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class BritPlexi50Normal(IntEnum):
    """Brit Plexi 50 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class Freeman100Lead(IntEnum):
    """Freeman 100 Lead (Guitar Amplifier)."""

    FAT = 0    # switch
    C45 = 1    # switch
    GAIN = 2    # float
    VOICE = 3    # switch
    SAT = 4    # switch
    BASS = 5    # float
    MID = 6    # float
    TREBLE = 7    # float
    MASTER = 8    # float
    PRESENCE = 9    # float
    OUTPUT = 10    # float dB


class UsTwnNormal(IntEnum):
    """US TWN Normal (Guitar Amplifier)."""

    VOLUME = 0    # float
    BRIGHT = 1    # switch
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    OUTPUT = 5    # float dB


class UsTwnVibrato(IntEnum):
    """US TWN Vibrato (Guitar Amplifier)."""

    VOLUME = 0    # float
    BRIGHT = 1    # switch
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    OUTPUT = 5    # float dB


class CaTremoOrange(IntEnum):
    """CA Tremo Orange (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class CaTremoRed(IntEnum):
    """CA Tremo Red (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class BritPlexi100Bright(IntEnum):
    """Brit Plexi 100 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class BritPlexi100Patch(IntEnum):
    """Brit Plexi 100 Patch (Guitar Amplifier)."""

    GAIN_1 = 0    # float
    GAIN_2 = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class BritPlexi100Normal(IntEnum):
    """Brit Plexi 100 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class UsSprNormal(IntEnum):
    """US SPR Normal (Guitar Amplifier)."""

    VOLUME = 0    # float
    BRIGHT = 1    # switch
    BASS = 2    # float
    TREBLE = 3    # float
    OUTPUT = 4    # float dB


class UsSprVibrato(IntEnum):
    """US SPR Vibrato (Guitar Amplifier)."""

    VOLUME = 0    # float
    BRIGHT = 1    # switch
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    OUTPUT = 5    # float dB


class Ca1starClean50wNormal(IntEnum):
    """CA 1Star Clean 50W Normal (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    EQ = 3    # rotarySwitch
    GAIN = 4    # float
    MASTER = 5    # float
    PRESENCE = 6    # float
    OUTPUT = 7    # float dB


class Ca1starClean50wTweed(IntEnum):
    """CA 1Star Clean 50W Tweed (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    EQ = 3    # rotarySwitch
    GAIN = 4    # float
    MASTER = 5    # float
    PRESENCE = 6    # float
    OUTPUT = 7    # float dB


class Ca1starClean100wNormal(IntEnum):
    """CA 1Star Clean 100W Normal (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    EQ = 3    # rotarySwitch
    GAIN = 4    # float
    MASTER = 5    # float
    PRESENCE = 6    # float
    OUTPUT = 7    # float dB


class Ca1starClean100wTweed(IntEnum):
    """CA 1Star Clean 100W Tweed (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    EQ = 3    # rotarySwitch
    GAIN = 4    # float
    MASTER = 5    # float
    PRESENCE = 6    # float
    OUTPUT = 7    # float dB


class Ca1starDrive50wNormal(IntEnum):
    """CA 1Star Drive 50W Normal (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    DRIVE = 3    # float
    EQ = 4    # rotarySwitch
    GAIN = 5    # float
    MASTER = 6    # float
    PRESENCE = 7    # float
    OUTPUT = 8    # float dB


class Ca1starDrive50wTweed(IntEnum):
    """CA 1Star Drive 50W Tweed (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    DRIVE = 3    # float
    EQ = 4    # rotarySwitch
    GAIN = 5    # float
    MASTER = 6    # float
    PRESENCE = 7    # float
    OUTPUT = 8    # float dB


class Ca1starDrive100wNormal(IntEnum):
    """CA 1Star Drive 100W Normal (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    DRIVE = 3    # float
    EQ = 4    # rotarySwitch
    GAIN = 5    # float
    MASTER = 6    # float
    PRESENCE = 7    # float
    OUTPUT = 8    # float dB


class Ca1starDrive100wTweed(IntEnum):
    """CA 1Star Drive 100W Tweed (Guitar Amplifier)."""

    BASS = 0    # float
    MID = 1    # float
    TREBLE = 2    # float
    DRIVE = 3    # float
    EQ = 4    # rotarySwitch
    GAIN = 5    # float
    MASTER = 6    # float
    PRESENCE = 7    # float
    OUTPUT = 8    # float dB


class Pv505Rhythm(IntEnum):
    """PV-505 Rhythm (Guitar Amplifier)."""

    GAIN = 0    # float
    BRIGHT = 1    # switch
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    MASTER = 5    # float
    PRESENCE = 6    # float
    DEPTH = 7    # float
    OUTPUT = 8    # float dB


class Captain50(IntEnum):
    """Captain 50 (Guitar Amplifier)."""

    BRIGHT = 0    # switch
    LOW_BOOST = 1    # switch
    GAIN = 2    # float
    BASS = 3    # float
    MID = 4    # float
    TREBLE = 5    # float
    MASTER = 6    # float
    OUTPUT = 7    # float dB


class BognaVishnu20thClean(IntEnum):
    """Bogna Vishnu 20th Clean (Guitar Amplifier)."""

    BRIGHT = 0    # switch
    GAIN = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    MASTER = 5    # float
    PRESENCE = 6    # float
    DEPTH = 7    # float
    OUTPUT = 8    # float dB


class Ev101iiisBlue6l6100w(IntEnum):
    """EV101IIIS Blue 6L6 100W (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    RESONANCE = 6    # float
    OUTPUT = 7    # float dB


class Ev101iiisRed6l6100w(IntEnum):
    """EV101IIIS Red 6L6 100W (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    RESONANCE = 6    # float
    OUTPUT = 7    # float dB


class UsPrince(IntEnum):
    """US Prince (Guitar Amplifier)."""

    VOLUME = 0    # float
    TREBLE = 1    # float
    BASS = 2    # float
    OUTPUT = 3    # float dB


class BritUblLead(IntEnum):
    """Brit UBL Lead (Guitar Amplifier)."""

    INPUT_GAIN = 0    # float
    LEAD_MASTER = 1    # float
    OUTPUT_MASTER = 2    # float
    BASS = 3    # float
    MID = 4    # float
    TREBLE = 5    # float
    PRESENCE = 6    # float
    OUTPUT = 7    # float dB


class BritUblLeadClip(IntEnum):
    """Brit UBL Lead Clip (Guitar Amplifier)."""

    INPUT_GAIN = 0    # float
    LEAD_MASTER = 1    # float
    OUTPUT_MASTER = 2    # float
    BASS = 3    # float
    MID = 4    # float
    TREBLE = 5    # float
    PRESENCE = 6    # float
    OUTPUT = 7    # float dB


class UsTweedBassladBrightPatch(IntEnum):
    """US Tweed Basslad Bright Patch (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsTweedBassladBright(IntEnum):
    """US Tweed Basslad Bright (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsTweedBassladNormalPatch(IntEnum):
    """US Tweed Basslad Normal Patch (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsTweedBassladNormal(IntEnum):
    """US Tweed Basslad Normal (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UkC15Normal(IntEnum):
    """UK C15 Normal (Guitar Amplifier)."""

    BRIGHT = 0    # switch
    VOLUME = 1    # float
    TONE_CUT = 2    # float
    OUTPUT = 3    # float dB


class UkC15Topboost(IntEnum):
    """UK C15 TopBoost (Guitar Amplifier)."""

    VOLUME = 0    # float
    BOOST = 1    # switch
    BASS = 2    # float
    TREBLE = 3    # float
    TONE_CUT = 4    # float
    OUTPUT = 5    # float dB


class UsHpTweedTwnNormal(IntEnum):
    """US HP Tweed TWN Normal (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsHpTweedTwnNormalPatch(IntEnum):
    """US HP Tweed TWN Normal Patch (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsHpTweedTwnBright(IntEnum):
    """US HP Tweed TWN Bright (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsHpTweedTwnBrightPatch(IntEnum):
    """US HP Tweed TWN Bright Patch (Guitar Amplifier)."""

    VOLUME_NORMAL = 0    # float
    VOLUME_BRIGHT = 1    # float
    TREBLE = 2    # float
    BASS = 3    # float
    MID = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class DCellHisbertCh1(IntEnum):
    """D-Cell Hisbert Ch1 (Guitar Amplifier)."""

    VOLUME = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MIDCUT = 4    # switch
    LEVEL = 5    # float
    INTENSITY = 6    # float
    MASTER = 7    # float
    PRESENCE = 8    # float
    DEEP = 9    # float
    OUTPUT = 10    # float dB


class DCellHisbertCh2(IntEnum):
    """D-Cell Hisbert Ch2 (Guitar Amplifier)."""

    GAIN = 0    # float
    MODE = 1    # switch
    VOLUME = 2    # float
    BASS = 3    # float
    MID = 4    # float
    TREBLE = 5    # float
    MIDCUT = 6    # switch
    LEVEL = 7    # float
    INTENSITY = 8    # float
    MASTER = 9    # float
    PRESENCE = 10    # float
    DEEP = 11    # float
    OUTPUT = 12    # float dB


class DCellHisbertCh3(IntEnum):
    """D-Cell Hisbert Ch3 (Guitar Amplifier)."""

    GAIN = 0    # float
    VOLUME = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    MIDCUT = 5    # switch
    LEVEL = 6    # float
    INTENSITY = 7    # float
    MASTER = 8    # float
    PRESENCE = 9    # float
    DEEP = 10    # float
    OUTPUT = 11    # float dB


class CaJohnS2cCh1(IntEnum):
    """CA John's 2C Ch1 (Guitar Amplifier)."""

    GAIN = 0    # float
    MASTER = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB
    DUMMY1 = 7    # empty
    DUMMY2 = 8    # empty
    DUMMY3 = 9    # empty
    N80_HZ = 10    # fader
    N240_HZ = 11    # fader
    N750_HZ = 12    # fader
    N2200_HZ = 13    # fader
    N6600_HZ = 14    # fader


class CaJohnS2cCh2(IntEnum):
    """CA John's 2C Ch2 (Guitar Amplifier)."""

    GAIN = 0    # float
    GAIN_PULL = 1    # switch
    SHRED = 2    # switch
    MASTER = 3    # float
    OUTPUT = 4    # float dB
    BASS = 5    # float
    MID = 6    # float
    TREBLE = 7    # float
    PRESENCE = 8    # float
    PRES_PULL = 9    # switch
    N80_HZ = 10    # fader
    N240_HZ = 11    # fader
    N750_HZ = 12    # fader
    N2200_HZ = 13    # fader
    N6600_HZ = 14    # fader
    MUTE_TRIG = 15    # switch


class CaJohnS2cCh3(IntEnum):
    """CA John's 2C Ch3 (Guitar Amplifier)."""

    GAIN = 0    # float
    GAIN_PULL = 1    # switch
    SHRED = 2    # switch
    MASTER = 3    # float
    OUTPUT = 4    # float dB
    BASS = 5    # float
    MID = 6    # float
    TREBLE = 7    # float
    PRESENCE = 8    # float
    PRES_PULL = 9    # switch
    N80_HZ = 10    # fader
    N240_HZ = 11    # fader
    N750_HZ = 12    # fader
    N2200_HZ = 13    # fader
    N6600_HZ = 14    # fader
    MUTE_TRIG = 15    # switch


class DCellH4Ch1Bright(IntEnum):
    """D-Cell H4 Ch1 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch1Normal(IntEnum):
    """D-Cell H4 Ch1 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch2Bright(IntEnum):
    """D-Cell H4 Ch2 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch2Normal(IntEnum):
    """D-Cell H4 Ch2 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch3(IntEnum):
    """D-Cell H4 Ch3 (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch4(IntEnum):
    """D-Cell H4 Ch4 (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class Ev101iiisRedEl34100w(IntEnum):
    """EV101IIIS Red EL34 100W (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    RESONANCE = 6    # float
    OUTPUT = 7    # float dB


class Ev101iiisBlueEl34100w(IntEnum):
    """EV101IIIS Blue EL34 100W (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    RESONANCE = 6    # float
    OUTPUT = 7    # float dB


class Solo100Lead(IntEnum):
    """Solo 100 Lead (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class Solo100CrunchBright(IntEnum):
    """Solo 100 Crunch Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class Solo100CrunchNormal(IntEnum):
    """Solo 100 Crunch Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class MatchmoreJefe(IntEnum):
    """Matchmore Jefe (Guitar Amplifier)."""

    VOLUME = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    BRILLIANCE = 4    # float
    MASTER = 5    # float
    OUTPUT = 6    # float dB


class MatchmoreD30Ch1(IntEnum):
    """Matchmore D30 Ch1 (Guitar Amplifier)."""

    VOLUME = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    CUT = 3    # float
    MASTER = 4    # float
    OUTPUT = 5    # float dB


class MatchmoreD30Ch2(IntEnum):
    """Matchmore D30 Ch2 (Guitar Amplifier)."""

    VOLUME = 0    # float
    CUT = 1    # float
    MASTER = 2    # float
    TONE = 3    # float
    OUTPUT = 4    # float dB


class VictorSquidCh1(IntEnum):
    """Victor Squid Ch1 (Guitar Amplifier)."""

    MOD = 0    # switch
    GAIN = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    MASTER = 5    # float
    FOCUS = 6    # switch
    H = 7    # switch
    B = 8    # switch
    TUBE = 9    # switch
    OUTPUT = 10    # float dB
    MUTE_TRIG = 11    # switch


class VictorSquidCh2(IntEnum):
    """Victor Squid Ch2 (Guitar Amplifier)."""

    MOD = 0    # switch
    GAIN = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    MASTER = 5    # float
    FOCUS = 6    # switch
    TIGHT = 7    # float
    PRESENCE = 8    # float
    TUBE = 9    # switch
    OUTPUT = 10    # float dB
    MUTE_TRIG = 11    # switch


class UsDlx64Vintage(IntEnum):
    """US DLX 64 Vintage (Guitar Amplifier)."""

    INPUT = 0    # switch
    MODE = 1    # comboBox
    VOLUME = 2    # float
    TREBLE = 3    # float
    BASS = 4    # float
    OUTPUT = 5    # float dB
    MUTE_TRIG = 6    # switch
    DELAY = 7    # int


class UsDlx65Reissue(IntEnum):
    """US DLX 65 Reissue (Guitar Amplifier)."""

    INPUT = 0    # switch
    MODE = 1    # comboBox
    VOLUME = 2    # float
    TREBLE = 3    # float
    BASS = 4    # float
    OUTPUT = 5    # float dB
    MUTE_TRIG = 6    # switch
    DELAY = 7    # int


class DumbbellOds(IntEnum):
    """Dumbbell ODS (Guitar Amplifier)."""

    CHANNEL = 0    # switch
    VOLUME = 1    # float
    TREBLE = 2    # float
    MIDDLE = 3    # float
    BASS = 4    # float
    OD_CONTENT = 5    # float
    OD_VOLUME = 6    # float
    MASTER = 7    # float
    PRESENCE = 8    # float
    PREAMP = 9    # switch
    BRIGHT = 10    # switch
    MID = 11    # switch
    EQ = 12    # switch
    OUTPUT = 13    # float dB


class BritBass50Bright(IntEnum):
    """Brit Bass 50 Bright (Bass Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class BritBass50Patch(IntEnum):
    """Brit Bass 50 Patch (Bass Amplifier)."""

    GAIN_1 = 0    # float
    GAIN_2 = 1    # float
    BASS = 2    # float
    MID = 3    # float
    TREBLE = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class BritBass50Normal(IntEnum):
    """Brit Bass 50 Normal (Bass Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    PRESENCE = 4    # float
    OUTPUT = 5    # float dB


class G800k(IntEnum):
    """G800K (Bass Amplifier)."""

    GAIN = 0    # float
    N10_DB = 1    # switch
    LO_CUT = 2    # switch
    HIGH_BOOST = 3    # switch
    MID_CONTOUR = 4    # switch
    BASS = 5    # float
    LO_MID = 6    # float
    HI_MID = 7    # float
    TREBLE = 8    # float
    OUTPUT = 9    # float dB


class Ca400Ch1(IntEnum):
    """CA 400+ Ch1 (Bass Amplifier)."""

    GAIN = 0    # float
    BRIGHT = 1    # switch
    TREBLE_SHIFT = 2    # switch
    BASS_SHIFT = 3    # switch
    BASS = 4    # float
    MID = 5    # float
    TREBLE = 6    # float
    MASTER = 7    # float
    EQ = 8    # switch
    OUTPUT = 9    # float dB
    N40_HZ = 10    # float
    N100_HZ = 11    # float
    N250_HZ = 12    # float
    N625_HZ = 13    # float
    N1560_HZ = 14    # float
    N3900_HZ = 15    # float
    N6600_HZ = 16    # float


class Ca400Ch2(IntEnum):
    """CA 400+ Ch2 (Bass Amplifier)."""

    GAIN = 0    # float
    BRIGHT = 1    # switch
    TREBLE_SHIFT = 2    # switch
    BASS_SHIFT = 3    # switch
    BASS = 4    # float
    MID = 5    # float
    TREBLE = 6    # float
    MASTER = 7    # float
    EQ = 8    # switch
    OUTPUT = 9    # float dB
    N40_HZ = 10    # float
    N100_HZ = 11    # float
    N250_HZ = 12    # float
    N625_HZ = 13    # float
    N1560_HZ = 14    # float
    N3900_HZ = 15    # float
    N6600_HZ = 16    # float


class AmpedSuperValve(IntEnum):
    """Amped Super Valve (Bass Amplifier)."""

    GAIN = 0    # float
    ULTRA_LO = 1    # switch
    ULTRA_HI = 2    # switch
    BASS = 3    # float
    MIDRANGE = 4    # float
    FREQUENCY = 5    # rotarySwitch
    TREBLE = 6    # float
    MASTER = 7    # float
    OUTPUT = 8    # float dB


class AmpedFlipTop6464(IntEnum):
    """Amped Flip-Top 6464 (Bass Amplifier)."""

    BASS = 0    # float
    TREBLE = 1    # float
    MASTER = 2    # float
    OUTPUT = 3    # float dB


class AmpedFlipTop6466(IntEnum):
    """Amped Flip-Top 6466 (Bass Amplifier)."""

    BASS = 0    # float
    TREBLE = 1    # float
    MASTER = 2    # float
    OUTPUT = 3    # float dB


class AmpedFlipTop6664(IntEnum):
    """Amped Flip-Top 6664 (Bass Amplifier)."""

    BASS = 0    # float
    TREBLE = 1    # float
    MASTER = 2    # float
    OUTPUT = 3    # float dB


class AmpedFlipTop6666(IntEnum):
    """Amped Flip-Top 6666 (Bass Amplifier)."""

    BASS = 0    # float
    TREBLE = 1    # float
    MASTER = 2    # float
    OUTPUT = 3    # float dB


class WattBassModNormal(IntEnum):
    """Watt Bass Mod Normal (Bass Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class WattBassModBright(IntEnum):
    """Watt Bass Mod Bright (Bass Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class MicrotubesB3k(IntEnum):
    """Microtubes® B3K (Bass Overdrive)."""

    DRIVE = 0    # float
    GROWL = 1    # switch
    MIDBOOST = 2    # switch
    TONE = 3    # float
    LEVEL = 4    # float
    BLEND = 5    # float


class Bddi(IntEnum):
    """BDDI (Bass Overdrive)."""

    BLEND = 0    # float
    PRESENCE = 1    # float
    DRIVE = 2    # float
    LEVEL = 3    # float
    TREBLE = 4    # float
    BASS = 5    # float


class SovietFuzz(IntEnum):
    """Soviet Fuzz (Bass Overdrive)."""

    SUSTAIN = 0    # float
    TONE = 1    # float
    VOLUME = 2    # float


class MicrotubesVmt(IntEnum):
    """Microtubes® VMT (Bass Overdrive)."""

    DRIVE = 0    # float
    ERA = 1    # float
    LEVEL = 2    # float
    BLEND = 3    # float


class ExoticBassZBoost(IntEnum):
    """Exotic Bass Z Boost (Bass Overdrive)."""

    GAIN = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    VOLUME = 3    # float


class Parametric8(IntEnum):
    """Parametric-8 (Equalizer)."""

    N1_GAIN = 0    # float dB
    N1_FREQ = 1    # float Hz
    N1_Q = 2    # float
    N1_TYPE = 3    # float
    N1_BYPASS = 4    # switch
    N2_GAIN = 5    # float dB
    N2_FREQ = 6    # float Hz
    N2_Q = 7    # float
    N2_TYPE = 8    # float
    N2_BYPASS = 9    # switch
    N3_GAIN = 10    # float dB
    N3_FREQ = 11    # float Hz
    N3_Q = 12    # float
    N3_TYPE = 13    # float
    N3_BYPASS = 14    # switch
    N4_GAIN = 15    # float dB
    N4_FREQ = 16    # float Hz
    N4_Q = 17    # float
    N4_TYPE = 18    # float
    N4_BYPASS = 19    # switch
    N5_GAIN = 20    # float dB
    N5_FREQ = 21    # float Hz
    N5_Q = 22    # float
    N5_TYPE = 23    # float
    N5_BYPASS = 24    # switch
    N6_GAIN = 25    # float dB
    N6_FREQ = 26    # float Hz
    N6_Q = 27    # float
    N6_TYPE = 28    # float
    N6_BYPASS = 29    # switch
    N7_GAIN = 30    # float dB
    N7_FREQ = 31    # float Hz
    N7_Q = 32    # float
    N7_TYPE = 33    # float
    N7_BYPASS = 34    # switch
    N8_GAIN = 35    # float dB
    N8_FREQ = 36    # float Hz
    N8_Q = 37    # float
    N8_TYPE = 38    # float
    N8_BYPASS = 39    # switch
    OUTPUT = 40    # float dB


class Parametric3(IntEnum):
    """Parametric-3 (Equalizer)."""

    N1_GAIN = 0    # float dB
    N1_FREQ = 1    # float Hz
    N1_Q = 2    # float
    N1_TYPE = 3    # float
    N1_BYPASS = 4    # switch
    N2_GAIN = 5    # float dB
    N2_FREQ = 6    # float Hz
    N2_Q = 7    # float
    N2_TYPE = 8    # float
    N2_BYPASS = 9    # switch
    N3_GAIN = 10    # float dB
    N3_FREQ = 11    # float Hz
    N3_Q = 12    # float
    N3_TYPE = 13    # float
    N3_BYPASS = 14    # switch
    OUTPUT = 15    # float dB


class LowHighCut(IntEnum):
    """Low-High Cut (Equalizer)."""

    HPF_SLOPE = 0    # rotarySwitch dB/oct
    HPF_FREQ = 1    # float Hz
    LPF_SLOPE = 2    # rotarySwitch dB/oct
    LPF_FREQ = 3    # float Hz
    OUTPUT = 4    # float dB


class Graphic9(IntEnum):
    """Graphic-9 (Equalizer)."""

    HPF = 0    # float Hz
    N65HZ = 1    # fader dB
    N125HZ = 2    # fader dB
    N250HZ = 3    # fader dB
    N500HZ = 4    # fader dB
    N1KHZ = 5    # fader dB
    N2KHZ = 6    # fader dB
    N4KHZ = 7    # fader dB
    N8KHZ = 8    # fader dB
    N16KHZ = 9    # fader dB
    LPF = 10    # float Hz
    Q = 11    # float
    OUTPUT = 12    # float dB


class PluginGraphic9(IntEnum):
    """Plugin Graphic-9 (Equalizer)."""

    HPF = 0    # float Hz
    N65HZ = 1    # fader dB
    N125HZ = 2    # fader dB
    N250HZ = 3    # fader dB
    N500HZ = 4    # fader dB
    N1KHZ = 5    # fader dB
    N2KHZ = 6    # fader dB
    N4KHZ = 7    # fader dB
    N8KHZ = 8    # fader dB
    N16KHZ = 9    # fader dB
    LPF = 10    # float Hz
    Q = 11    # float
    OUTPUT = 12    # float dB


class Legendary87M(IntEnum):
    """Legendary 87 (M) (Compressor)."""

    INPUT = 0    # float dB
    RATIO = 1    # rotarySwitch
    ATTACK = 2    # float ms
    RELEASE = 3    # float s
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class SolidStateCompM(IntEnum):
    """Solid State Comp (M) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # rotarySwitch
    ATTACK = 2    # float ms
    RELEASE = 3    # float s
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class VcaCompM(IntEnum):
    """VCA Comp (M) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # float
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class OptoCompM(IntEnum):
    """Opto Comp (M) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # float
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class Jewel(IntEnum):
    """Jewel (Compressor)."""

    COMP = 0    # float
    EQ = 1    # float
    VOLUME = 2    # float
    HIGH_CUT = 3    # switch
    MIX = 4    # float %


class Legendary87St(IntEnum):
    """Legendary 87 (ST) (Compressor)."""

    INPUT = 0    # float dB
    RATIO = 1    # rotarySwitch
    ATTACK = 2    # float ms
    RELEASE = 3    # float s
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class SolidStateCompSt(IntEnum):
    """Solid State Comp (ST) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # rotarySwitch
    ATTACK = 2    # float ms
    RELEASE = 3    # float s
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class VcaCompSt(IntEnum):
    """VCA Comp (ST) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # float
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class OptoCompSt(IntEnum):
    """Opto Comp (ST) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # float
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    GAIN_REDUCTION = 6    # grMeter dB


class ChiefCs3(IntEnum):
    """Chief CS3 (Compressor)."""

    SUSTAIN = 0    # float
    ATTACK = 1    # float
    TONE = 2    # float
    LEVEL = 3    # float


class SolidStateCompSC(IntEnum):
    """Solid State Comp (S/C) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # rotarySwitch
    ATTACK = 2    # float ms
    RELEASE = 3    # float s
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    SOURCE = 6    # comboBox
    GAIN_REDUCTION = 7    # grMeter dB


class Legendary87SC(IntEnum):
    """Legendary 87 (S/C) (Compressor)."""

    INPUT = 0    # float dB
    RATIO = 1    # rotarySwitch
    ATTACK = 2    # float ms
    RELEASE = 3    # float s
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    SOURCE = 6    # comboBox
    GAIN_REDUCTION = 7    # grMeter dB


class OptoCompSC(IntEnum):
    """Opto Comp (S/C) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # float
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    SOURCE = 6    # comboBox
    GAIN_REDUCTION = 7    # grMeter dB


class VcaCompSC(IntEnum):
    """VCA Comp (S/C) (Compressor)."""

    THRESHOLD = 0    # float dB
    RATIO = 1    # float
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    MAKEUP = 4    # float dB
    MIX = 5    # float %
    SOURCE = 6    # comboBox
    GAIN_REDUCTION = 7    # grMeter dB


class AnalogDelayM(IntEnum):
    """Analog Delay (M) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    QUALITY = 4    # rotarySwitch
    SYNC = 5    # switch
    SYNC_NOTE = 6    # rotarySwitch
    DELAY_TIME = 7    # float ms
    MOD_RATE = 8    # float Hz
    MOD_DEPTH = 9    # float %
    DRIVE = 10    # float %
    TRAILS = 11    # switch
    DYN_DEPTH = 12    # float dB
    DYN_MODE = 13    # rotarySwitch
    THRESHOLD = 14    # float dB
    ATTACK = 15    # float ms
    RELEASE = 16    # float ms
    KNEE = 17    # float dB
    FEEDBACK_DEPTH = 18    # float %
    GAIN_REDUCTION = 19    # grMeter dB


class SimplePingPongDelay(IntEnum):
    """Simple Ping Pong Delay (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    TONE = 2    # float
    SYNC = 3    # switch
    SYNC_NOTE = 4    # rotarySwitch
    DELAY_TIME = 5    # float ms
    TRAILS = 6    # switch
    STEREO_WIDTH = 7    # float %


class SimpleDelaySt(IntEnum):
    """Simple Delay (ST) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    TONE = 2    # float
    SYNC = 3    # switch
    SYNC_NOTE = 4    # rotarySwitch
    DELAY_TIME = 5    # float ms
    TRAILS = 6    # switch


class TapeDelaySt(IntEnum):
    """Tape Delay (ST) (Delay)."""

    NOTIFICATION_START = 0    # float
    MIX = 1    # float %
    FEEDBACK = 2    # float %
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    PING_PONG = 5    # switch
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch
    DELAY_TIME = 8    # float ms
    WOW = 9    # float %
    FLUTTER = 10    # float %
    DRIVE = 11    # float %
    TRAILS = 12    # switch
    DUMMY = 13    # float %
    STEREO_WIDTH = 14    # float %
    DYN_DEPTH = 15    # float dB
    DYN_MODE = 16    # rotarySwitch
    THRESHOLD = 17    # float dB
    ATTACK = 18    # float ms
    RELEASE = 19    # float ms
    KNEE = 20    # float dB
    FEEDBACK_DEPTH = 21    # float %
    GAIN_REDUCTION = 22    # grMeter dB
    NOTIFICATION_END = 23    # float


class DigitalDelayM(IntEnum):
    """Digital Delay (M) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    SYNC = 4    # switch
    SYNC_NOTE = 5    # rotarySwitch
    DELAY_TIME = 6    # float ms
    MOD_RATE = 7    # float Hz
    MOD_DEPTH = 8    # float %
    TRAILS = 9    # switch
    DYN_DEPTH = 10    # float dB
    DYN_MODE = 11    # rotarySwitch
    THRESHOLD = 12    # float dB
    ATTACK = 13    # float ms
    RELEASE = 14    # float ms
    KNEE = 15    # float dB
    FEEDBACK_DEPTH = 16    # float %
    GAIN_REDUCTION = 17    # grMeter dB


class SimpleDelayM(IntEnum):
    """Simple Delay (M) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    TONE = 2    # float
    SYNC = 3    # switch
    SYNC_NOTE = 4    # rotarySwitch
    DELAY_TIME = 5    # float ms
    TRAILS = 6    # switch


class TapeDelayM(IntEnum):
    """Tape Delay (M) (Delay)."""

    NOTIFICATION_START = 0    # float
    MIX = 1    # float %
    FEEDBACK = 2    # float %
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    SYNC = 5    # switch
    SYNC_NOTE = 6    # rotarySwitch
    DELAY_TIME = 7    # float ms
    WOW = 8    # float %
    FLUTTER = 9    # float %
    DRIVE = 10    # float %
    TRAILS = 11    # switch
    DUMMY = 12    # float
    DYN_DEPTH = 13    # float dB
    DYN_MODE = 14    # rotarySwitch
    THRESHOLD = 15    # float dB
    ATTACK = 16    # float ms
    RELEASE = 17    # float ms
    KNEE = 18    # float dB
    FEEDBACK_DEPTH = 19    # float %
    GAIN_REDUCTION = 20    # grMeter dB
    NOTIFICATION_END = 21    # float


class SlapbackDelaySt(IntEnum):
    """Slapback Delay (ST) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    PING_PONG = 4    # switch
    QUALITY = 5    # rotarySwitch
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch
    DELAY_TIME = 8    # float ms
    MOD_RATE = 9    # float Hz
    MOD_DEPTH = 10    # float %
    WIDTH = 11    # float %
    DRIVE = 12    # float %
    TRAILS = 13    # switch
    DYN_DEPTH = 14    # float dB
    DYN_MODE = 15    # rotarySwitch
    THRESHOLD = 16    # float dB
    ATTACK = 17    # float ms
    RELEASE = 18    # float ms
    KNEE = 19    # float dB
    FEEDBACK_DEPTH = 20    # float %
    GAIN_REDUCTION = 21    # grMeter dB
    STEREO_WIDTH = 22    # float %


class SlapbackDelayM(IntEnum):
    """Slapback Delay (M) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    QUALITY = 4    # rotarySwitch
    SYNC = 5    # switch
    SYNC_NOTE = 6    # rotarySwitch
    DELAY_TIME = 7    # float ms
    MOD_RATE = 8    # float Hz
    MOD_DEPTH = 9    # float %
    DRIVE = 10    # float %
    TRAILS = 11    # switch
    DYN_DEPTH = 12    # float dB
    DYN_MODE = 13    # rotarySwitch
    THRESHOLD = 14    # float dB
    ATTACK = 15    # float ms
    RELEASE = 16    # float ms
    KNEE = 17    # float dB
    FEEDBACK_DEPTH = 18    # float %
    GAIN_REDUCTION = 19    # grMeter dB


class AnalogDelaySt(IntEnum):
    """Analog Delay (ST) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    PING_PONG = 4    # switch
    QUALITY = 5    # rotarySwitch
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch
    DELAY_TIME = 8    # float ms
    MOD_RATE = 9    # float Hz
    MOD_DEPTH = 10    # float %
    WIDTH = 11    # float %
    DRIVE = 12    # float %
    TRAILS = 13    # switch
    DYN_DEPTH = 14    # float dB
    DYN_MODE = 15    # rotarySwitch
    THRESHOLD = 16    # float dB
    ATTACK = 17    # float ms
    RELEASE = 18    # float ms
    KNEE = 19    # float dB
    FEEDBACK_DEPTH = 20    # float %
    GAIN_REDUCTION = 21    # grMeter dB
    STEREO_WIDTH = 22    # float %


class DigitalDelaySt(IntEnum):
    """Digital Delay (ST) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    PING_PONG = 4    # switch
    SYNC = 5    # switch
    SYNC_NOTE = 6    # rotarySwitch
    DELAY_TIME = 7    # float ms
    MOD_RATE = 8    # float Hz
    MOD_DEPTH = 9    # float %
    WIDTH = 10    # float %
    TRAILS = 11    # switch
    DYN_DEPTH = 12    # float dB
    DYN_MODE = 13    # rotarySwitch
    THRESHOLD = 14    # float dB
    ATTACK = 15    # float ms
    RELEASE = 16    # float ms
    KNEE = 17    # float dB
    FEEDBACK_DEPTH = 18    # float %
    GAIN_REDUCTION = 19    # grMeter dB
    STEREO_WIDTH = 20    # float %


class DualDelay(IntEnum):
    """Dual Delay (Delay)."""

    MIX = 0    # float %
    SYNC_L = 1    # switch
    SYNC_NOTE_L = 2    # rotarySwitch
    DELAY_TIME_L = 3    # float ms
    FEEDBACK_L = 4    # float %
    X_FEEDBACK = 5    # float %
    SYNC_R = 6    # switch
    SYNC_NOTE_R = 7    # rotarySwitch
    DELAY_TIME_R = 8    # float ms
    FEEDBACK_R = 9    # float %
    HIGH_PASS = 10    # float Hz
    LOW_PASS = 11    # float Hz
    MOD_RATE = 12    # float Hz
    MOD_DEPTH = 13    # float %
    LINK_FBACK = 14    # switch
    TRAILS = 15    # switch
    DYN_DEPTH = 16    # float dB
    DYN_MODE = 17    # rotarySwitch
    THRESHOLD = 18    # float dB
    ATTACK = 19    # float ms
    RELEASE = 20    # float ms
    KNEE = 21    # float dB
    FEEDBACK_DEPTH = 22    # float %
    GAIN_REDUCTION = 23    # grMeter dB
    STEREO_WIDTH = 24    # float %


class ReverseDelayM(IntEnum):
    """Reverse Delay (M) (Delay)."""

    MIX = 0    # float %
    FEEDBACK = 1    # float %
    FEEDBACK_MODE = 2    # switch
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    SYNC = 5    # switch
    SYNC_NOTE = 6    # rotarySwitch
    DELAY_TIME = 7    # float ms
    OVERLAP = 8    # float %
    TRIG_THRESHOLD = 9    # floatWithLed dB
    DYN_DEPTH = 10    # float dB
    DYN_MODE = 11    # rotarySwitch
    THRESHOLD = 12    # float dB
    ATTACK = 13    # float ms
    RELEASE = 14    # float ms
    KNEE = 15    # float dB
    FEEDBACK_DEPTH = 16    # float %
    GAIN_REDUCTION = 17    # grMeter dB
    TRAILS = 18    # switch


class DualReverseDelay(IntEnum):
    """Dual Reverse Delay (Delay)."""

    MIX = 0    # float %
    SYNC = 1    # switch
    SYNC_NOTE_L = 2    # rotarySwitch
    DELAY_TIME_L = 3    # float ms
    FEEDBACK_L = 4    # float %
    X_FEEDBACK = 5    # float %
    FEEDBACK_MODE = 6    # switch
    SYNC_NOTE_R = 7    # rotarySwitch
    DELAY_TIME_R = 8    # float ms
    FEEDBACK_R = 9    # float %
    OVERLAP = 10    # float %
    TRIG_THRESHOLD = 11    # floatWithLed dB
    DYN_DEPTH = 12    # float dB
    DYN_MODE = 13    # rotarySwitch
    THRESHOLD = 14    # float dB
    ATTACK = 15    # float ms
    RELEASE = 16    # float ms
    KNEE = 17    # float dB
    FEEDBACK_DEPTH = 18    # float %
    GAIN_REDUCTION = 19    # grMeter dB
    HIGH_PASS = 20    # float Hz
    LOW_PASS = 21    # float Hz
    STEREO_WIDTH = 22    # float %
    TRAILS = 23    # switch
    LINK_FBACK = 24    # switch


class CircularDelay(IntEnum):
    """Circular Delay (Delay)."""

    MIX = 0    # float %
    TAP_PRESET = 1    # rotarySwitch
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DELAY_TIME = 4    # float ms
    FEEDBACK = 5    # float %
    DIFFUSION = 6    # float %
    HIGH_PASS = 7    # float Hz
    LOW_PASS = 8    # float Hz
    MOD_RATE = 9    # float Hz
    MOD_DEPTH = 10    # float %
    VINTAGE_MODE = 11    # switch
    TRAILS = 12    # switch


class VintageChorus(IntEnum):
    """Vintage Chorus (Modulation)."""

    MIX = 0    # float %
    MODE = 1    # switch
    CHR_RATE = 2    # float Hz
    VIB_RATE = 3    # float Hz
    VIB_DEPTH = 4    # float %
    WIDTH = 5    # float %
    SYNC = 6    # switch
    CHR_NOTE = 7    # rotarySwitch
    VIB_NOTE = 8    # rotarySwitch


class DualChorus(IntEnum):
    """Dual Chorus (Modulation)."""

    MIX = 0    # float %
    MODE = 1    # switch
    RATE = 2    # float Hz
    DEPTH = 3    # float %
    WIDTH = 4    # float %
    TONE = 5    # float
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch


class Vibrato(IntEnum):
    """Vibrato (Modulation)."""

    RATE = 0    # float Hz
    DEPTH = 1    # float %
    WIDTH = 2    # float %
    LFO_ACTIVE = 3    # switch
    FADE_IN = 4    # float ms
    FADE_OUT = 5    # float ms
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch


class Flangerish(IntEnum):
    """Flangerish (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float Hz
    DEPTH = 2    # float %
    FEEDBACK = 3    # float %
    WIDTH = 4    # float %
    DRIVE = 5    # float %
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch


class Tremolo(IntEnum):
    """Tremolo (Modulation)."""

    RATE = 0    # float Hz
    DEPTH = 1    # float %
    WAVEFORM = 2    # comboBox
    DUTY_CYCLE = 3    # float %
    WIDTH = 4    # float %
    SMOOTHING = 5    # float %
    LFO_ACTIVE = 6    # switch
    FADE_IN = 7    # float ms
    FADE_OUT = 8    # float ms
    BOOST = 9    # float %
    SYNC = 10    # switch
    SYNC_NOTE = 11    # rotarySwitch


class Rotary(IntEnum):
    """Rotary (Modulation)."""

    SPEED = 0    # switch
    SLOW_SPEED = 1    # float Hz
    FAST_SPEED = 2    # float Hz
    ACCELERATION = 3    # float %
    SPEAKER_BALANCE = 4    # float %
    DRIVE = 5    # float %
    BRIGHTNESS = 6    # float %
    HORN_MIC_WIDTH = 7    # float %
    SYNC = 8    # switch
    SLOW_NOTE = 9    # rotarySwitch
    FAST_NOTE = 10    # rotarySwitch


class DigitalFlanger(IntEnum):
    """Digital Flanger (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float Hz
    DEPTH = 2    # float %
    DELAY = 3    # float ms
    FEEDBACK = 4    # float %
    POLARITY = 5    # switch
    WIDTH = 6    # float %
    DRIVE = 7    # float %
    VOLUME = 8    # float dB
    SYNC = 9    # switch
    SYNC_NOTE = 10    # rotarySwitch


class FlangerEngine(IntEnum):
    """Flanger Engine (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float Hz
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DELAY = 4    # float ms
    DEPTH = 5    # float %
    THR_ZERO = 6    # switch
    FEEDBACK = 7    # float %
    WAVEFORM = 8    # rotarySwitch
    DUTY_CYCLE = 9    # float
    SKEW = 10    # float
    SMOOTHING = 11    # float %
    LOW_PASS = 12    # float Hz
    HIGH_PASS = 13    # float Hz
    WIDTH = 14    # float %
    RESONANCE = 15    # rotarySwitch
    COLOR = 16    # rotarySwitch
    INTENSITY = 17    # float %
    DRIVE_TYPE = 18    # rotarySwitch
    DRIVE = 19    # float %
    OUTPUT = 20    # float dB


class ChorusEngine(IntEnum):
    """Chorus Engine (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float Hz
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DELAY = 4    # float ms
    DEPTH = 5    # float %
    MORPH = 6    # float %
    RANDOM = 7    # float %
    VOICE_MODE = 8    # rotarySwitch
    TONE = 9    # float %
    TONE_FREQ = 10    # float Hz
    LOW_PASS = 11    # float Hz
    HIGH_PASS = 12    # float Hz
    WIDTH = 13    # float %
    DRIVE_TYPE = 14    # rotarySwitch
    DRIVE = 15    # float %
    OUTPUT = 16    # float dB


class MxFlanger(IntEnum):
    """MX Flanger (Modulation)."""

    MIX = 0    # float %
    MANUAL = 1    # float %
    WIDTH = 2    # float %
    SPEED = 3    # float %
    SYNC = 4    # switch
    SYNC_NOTE = 5    # rotarySwitch
    REGEN = 6    # float %
    OUTPUT = 7    # float dB
    RATE = 8    # float
    DELAY = 9    # float
    DEPTH = 10    # float


class DreamChorusSt(IntEnum):
    """Dream Chorus (ST) (Modulation)."""

    MIX = 0    # float %
    SPEED = 1    # float %
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DEPTH = 4    # float %
    MODE = 5    # switch
    OUTPUT = 6    # float dB


class Chorus229t(IntEnum):
    """Chorus 229T (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float Hz
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DEPTH = 4    # float %
    WIDTH = 5    # float %
    OUTPUT = 6    # float dB


class ChiefCe2wSt(IntEnum):
    """Chief CE2W (ST) (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float %
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DEPTH = 4    # float %
    TYPE = 5    # switch
    WIDTH = 6    # float %
    OUTPUT = 7    # float dB


class ChiefCe2wM(IntEnum):
    """Chief CE2W (M) (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float %
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DEPTH = 4    # float %
    TYPE = 5    # switch
    OUT_MODE = 6    # switch
    OUTPUT = 7    # float dB


class DreamChorusM(IntEnum):
    """Dream Chorus (M) (Modulation)."""

    MIX = 0    # float %
    SPEED = 1    # float %
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    DEPTH = 4    # float %
    MODE = 5    # switch
    OUTPUT = 6    # float dB


class ChiefDc2wSt(IntEnum):
    """Chief DC2W (ST) (Modulation)."""

    MIX = 0    # float %
    MODE = 1    # rotarySwitch
    TYPE = 2    # switch
    DRIVE = 3    # float %
    OUTPUT = 4    # float dB
    STEREO = 5    # switch


class MxPhase95(IntEnum):
    """MX Phase 95 (Modulation)."""

    MIX = 0    # float %
    SPEED = 1    # float %
    SYNC = 2    # switch
    SYNC_NOTE = 3    # rotarySwitch
    TYPE = 4    # switch
    MODE = 5    # switch
    OUTPUT = 6    # float dB


class MxVibe(IntEnum):
    """MX Vibe (Modulation)."""

    MIX = 0    # float %
    VIBE = 1    # switch
    SPEED = 2    # float %
    SYNC = 3    # switch
    SYNC_NOTE = 4    # rotarySwitch
    LEVEL = 5    # float %
    DEPTH = 6    # float %
    OUTPUT = 7    # float dB


class ChiefDc2wM(IntEnum):
    """Chief DC2W (M) (Modulation)."""

    MIX = 0    # float %
    MODE = 1    # rotarySwitch
    TYPE = 2    # switch
    DRIVE = 3    # float %
    OUTPUT = 4    # float dB
    STEREO = 5    # switch


class Phaser(IntEnum):
    """Phaser (Modulation)."""

    MIX = 0    # float %
    SPEED = 1    # float
    WIDTH = 2    # float %
    DRIVE = 3    # float %
    DEPTH = 4    # float %
    MANUAL = 5    # float %
    RESONANCE = 6    # float %
    OUTPUT = 7    # float dB
    SYNC = 8    # switch
    SYNC_NOTE = 9    # rotarySwitch


class HarmonicTremolo(IntEnum):
    """Harmonic Tremolo (Modulation)."""

    RATE = 0    # float Hz
    DEPTH = 1    # float %
    WAVEFORM = 2    # comboBox
    DUTY_CYCLE = 3    # float %
    SMOOTHING = 4    # float %
    LFO_ACTIVE = 5    # switch
    FADE_IN = 6    # float ms
    FADE_OUT = 7    # float ms
    BOOST = 8    # float %
    LP_XOVER = 9    # float Hz
    HP_XOVER = 10    # float Hz
    SYNC = 11    # switch
    SYNC_NOTE = 12    # rotarySwitch
    SYNC_ON = 13    # switch


class MicroProcessorSt(IntEnum):
    """Micro Processor (ST) (Modulation)."""

    MIX = 0    # float %
    SYNC = 1    # switch
    DELAY_TIME_A = 2    # float ms
    DELAY_TIME_B = 3    # float ms
    SYNC_NOTE_A = 4    # rotarySwitch
    SYNC_NOTE_B = 5    # rotarySwitch
    MOD_SOURCE = 6    # comboBox
    LFO_RATE = 7    # float Hz
    MOD_DEPTH = 8    # float %
    ENV_GAIN = 9    # float dB
    FEEDBACK = 10    # float %
    X_FEEDBACK = 11    # switch
    PITCH_A = 12    # float cents
    PITCH_B = 13    # float cents
    A_B_PITCH_MIX = 14    # float %
    TONE = 15    # float %
    OUTPUT = 16    # float dB
    TRAILS = 17    # switch


class PatternTremolo(IntEnum):
    """Pattern Tremolo (Modulation)."""

    SYNC = 0    # switch
    RATE = 1    # float Hz
    SYNC_NOTE = 2    # rotarySwitch
    SWING = 3    # float %
    DEPTH = 4    # float %
    SMOOTH = 5    # float %
    PING_PONG = 6    # switch
    RETRIGGER = 7    # switch
    OUTPUT = 8    # float dB
    TRANSIENT_THRESHOLD = 9    # float dB
    STEPS = 10    # float
    STEP_1 = 11    # float
    STEP_2 = 12    # float
    STEP_3 = 13    # float
    STEP_4 = 14    # float
    STEP_5 = 15    # float
    STEP_6 = 16    # float
    STEP_7 = 17    # float
    STEP_8 = 18    # float
    STEP_9 = 19    # float
    STEP_10 = 20    # float
    STEP_11 = 21    # float
    STEP_12 = 22    # float
    STEP_13 = 23    # float
    STEP_14 = 24    # float
    STEP_15 = 25    # float
    STEP_16 = 26    # float
    STEP_1_CONNECTED = 27    # switch
    STEP_2_CONNECTED = 28    # switch
    STEP_3_CONNECTED = 29    # switch
    STEP_4_CONNECTED = 30    # switch
    STEP_5_CONNECTED = 31    # switch
    STEP_6_CONNECTED = 32    # switch
    STEP_7_CONNECTED = 33    # switch
    STEP_8_CONNECTED = 34    # switch
    STEP_9_CONNECTED = 35    # switch
    STEP_10_CONNECTED = 36    # switch
    STEP_11_CONNECTED = 37    # switch
    STEP_12_CONNECTED = 38    # switch
    STEP_13_CONNECTED = 39    # switch
    STEP_14_CONNECTED = 40    # switch
    STEP_15_CONNECTED = 41    # switch


class Room(IntEnum):
    """Room (Reverb)."""

    DECAY = 0    # float s
    PRE_DELAY = 1    # float ms
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    MIX = 4    # float %
    TRAILS = 5    # switch


class SpringSt(IntEnum):
    """Spring (ST) (Reverb)."""

    MIX = 0    # float %
    DAMPING = 1    # float %
    TONE = 2    # float %
    BOING = 3    # float %
    TRAILS = 4    # switch


class Hall(IntEnum):
    """Hall (Reverb)."""

    DECAY = 0    # float s
    PRE_DELAY = 1    # float ms
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    MIX = 4    # float %
    TRAILS = 5    # switch


class SpringM(IntEnum):
    """Spring (M) (Reverb)."""

    MIX = 0    # float %
    DAMPING = 1    # float %
    TONE = 2    # float %
    BOING = 3    # float %
    TRAILS = 4    # switch


class Modulated(IntEnum):
    """Modulated (Reverb)."""

    DECAY = 0    # float s
    PRE_DELAY = 1    # float ms
    MOD_SPEED = 2    # float Hz
    MOD_DEPTH = 3    # float %
    HIGH_PASS = 4    # float Hz
    LOW_PASS = 5    # float Hz
    MIX = 6    # float %
    TRAILS = 7    # switch


class Ambience(IntEnum):
    """Ambience (Reverb)."""

    SIZE = 0    # rotarySwitch
    PRE_DELAY = 1    # float ms
    HIGH_PASS = 2    # float Hz
    LOW_PASS = 3    # float Hz
    MIX = 4    # float %
    TRAILS = 5    # switch


class Cave(IntEnum):
    """Cave (Reverb)."""

    DECAY = 0    # float s
    PRE_DELAY = 1    # float ms
    DAMPING = 2    # float %
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    MIX = 5    # float %
    TRAILS = 6    # switch


class Shimmer(IntEnum):
    """Shimmer (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float s
    BRIGHTNESS = 2    # float %
    FEEDBACK = 3    # float %
    PITCH = 4    # float Semitones
    TRAILS = 5    # switch
    PRE_DELAY = 6    # float ms
    DAMPING = 7    # float %
    HIGH_PASS = 8    # float Hz
    RAND_PITCH = 9    # float Cents
    MOD_SPEED = 10    # float Hz
    MOD_DEPTH = 11    # float %
    WET_LEVEL = 12    # float dB


class MindHall(IntEnum):
    """Mind Hall (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float %
    PRE_DELAY = 2    # float ms
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    DAMPING = 5    # float %
    TRAILS = 6    # switch


class PlateLush(IntEnum):
    """Plate Lush (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float %
    PRE_DELAY = 2    # float ms
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    LF_DAMPING = 5    # float %
    HF_DAMPING = 6    # float %
    MOD_DEPTH = 7    # float %
    TRAILS = 8    # switch


class Plate(IntEnum):
    """Plate (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float %
    PRE_DELAY = 2    # float ms
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    LF_DAMPING = 5    # float %
    HF_DAMPING = 6    # float %
    MOD_DEPTH = 7    # float %
    TRAILS = 8    # switch


class PlateTight(IntEnum):
    """Plate Tight (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float %
    PRE_DELAY = 2    # float ms
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    LF_DAMPING = 5    # float %
    HF_DAMPING = 6    # float %
    MOD_DEPTH = 7    # float %
    TRAILS = 8    # switch


class SpringReverbEngineM(IntEnum):
    """Spring Reverb Engine (M) (Reverb)."""

    INPUT_GAIN = 0    # float dB
    HIGH_PASS = 1    # float Hz
    LOW_PASS = 2    # float Hz
    CHIRP_DECAY = 3    # float %
    DIFF_DECAY = 4    # float %
    CHIRP_LEVEL = 5    # float %
    DIFF_LEVEL = 6    # float %
    TANK_TYPE = 7    # comboBox
    MIX = 8    # float %
    OUTPUT_GAIN = 9    # float dB
    TRAILS = 10    # switch


class SpringReverbEngineSt(IntEnum):
    """Spring Reverb Engine (ST) (Reverb)."""

    INPUT_GAIN = 0    # float dB
    HIGH_PASS = 1    # float Hz
    LOW_PASS = 2    # float Hz
    CHIRP_DECAY = 3    # float %
    DIFF_DECAY = 4    # float %
    CHIRP_LEVEL = 5    # float %
    DIFF_LEVEL = 6    # float %
    TANK_TYPE = 7    # comboBox
    MIX = 8    # float %
    OUTPUT_GAIN = 9    # float dB
    TRAILS = 10    # switch


class NordicConcertHallSt(IntEnum):
    """Nordic Concert Hall (ST) (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float s
    PRE_DELAY = 2    # float ms
    SIZE = 3    # float %
    H_SHELF_GAIN = 4    # float dB
    HIGH_PASS = 5    # float Hz
    LOW_PASS = 6    # float Hz
    BASS_FREQ = 7    # float Hz
    BASS_MULT = 8    # float x
    H_SHELF_FREQ = 9    # float Hz
    REV_ATTACK = 10    # float %
    EARLY_DIFF = 11    # float %
    LATE_DIFF = 12    # float %
    MOD_RATE = 13    # float Hz
    MOD_DEPTH = 14    # float %
    TRAILS = 15    # switch


class StudioPlate70St(IntEnum):
    """Studio Plate 70 (ST) (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float s
    PRE_DELAY = 2    # float ms
    SIZE = 3    # float %
    H_SHELF_GAIN = 4    # float dB
    HIGH_PASS = 5    # float Hz
    LOW_PASS = 6    # float Hz
    BASS_FREQ = 7    # float Hz
    BASS_MULT = 8    # float x
    H_SHELF_FREQ = 9    # float Hz
    REV_ATTACK = 10    # float %
    EARLY_DIFF = 11    # float %
    LATE_DIFF = 12    # float %
    MOD_RATE = 13    # float Hz
    MOD_DEPTH = 14    # float %
    TRAILS = 15    # switch


class BlossomSt(IntEnum):
    """Blossom (ST) (Reverb)."""

    MIX = 0    # float %
    DECAY = 1    # float s
    PRE_DELAY = 2    # float ms
    HIGH_PASS = 3    # float Hz
    LOW_PASS = 4    # float Hz
    EXTRA_E_R = 5    # switch
    E_R_LENGTH = 6    # float %
    DIFFUSION = 7    # float %
    BASS = 8    # float dB
    TREBLE = 9    # float dB
    DUCKING = 10    # float %
    GAIN_REDUCTION = 11    # grMeter dB
    MODULATION = 12    # float %
    TRAILS = 13    # switch


class BubbaWah(IntEnum):
    """Bubba Wah (Wah)."""

    WAH = 0    # float


class BassWah(IntEnum):
    """Bass Wah (Wah)."""

    WAH = 0    # float


class CryingWah(IntEnum):
    """Crying Wah (Wah)."""

    WAH = 0    # float


class CryingClydeWah(IntEnum):
    """Crying Clyde Wah (Wah)."""

    WAH = 0    # float


class BadHorse(IntEnum):
    """Bad Horse (Wah)."""

    WAH = 0    # float


class CryingWahFromHell(IntEnum):
    """Crying Wah From Hell (Wah)."""

    WAH = 0    # float
    RANGE = 1    # float
    Q = 2    # float
    FINE_TUNE = 3    # float
    BOOST = 4    # switch
    BOOST_LEVEL = 5    # float dB


class AutoWah(IntEnum):
    """Auto Wah (Wah)."""

    SENSITIVITY = 0    # float %
    ATTACK = 1    # float ms
    RELEASE = 2    # float ms


class Send1(IntEnum):
    """Send 1 (FX Loop)."""

    LEVEL = 0    # float dB
    THRU = 1    # float dB


class Send2(IntEnum):
    """Send 2 (FX Loop)."""

    LEVEL = 0    # float dB
    THRU = 1    # float dB


class Return1(IntEnum):
    """Return 1 (FX Loop)."""

    LEVEL = 0    # float dB
    MIX = 1    # float %


class Return2(IntEnum):
    """Return 2 (FX Loop)."""

    LEVEL = 0    # float dB
    MIX = 1    # float %


class FxLoop1(IntEnum):
    """FX Loop 1 (FX Loop)."""

    SEND_LEV = 0    # float dB
    RET_LEV = 1    # float dB
    MIX = 2    # float %
    TRAILS = 3    # switch


class FxLoop2(IntEnum):
    """FX Loop 2 (FX Loop)."""

    SEND_LEV = 0    # float dB
    RET_LEV = 1    # float dB
    MIX = 2    # float %
    TRAILS = 3    # switch


class Send12(IntEnum):
    """Send 1/2 (FX Loop)."""

    LEVEL = 0    # float dB
    THRU = 1    # float dB


class Return12(IntEnum):
    """Return 1/2 (FX Loop)."""

    LEVEL = 0    # float dB
    MIX = 1    # float %


class FxLoop12(IntEnum):
    """FX Loop 1/2 (FX Loop)."""

    SEND_LEV = 0    # float dB
    RET_LEV = 1    # float dB
    MIX = 2    # float %
    TRAILS = 3    # switch


class AdaptiveGate(IntEnum):
    """Adaptive Gate (Utility)."""

    NOISE_REDUCTION = 0    # float %


class UtilityGate(IntEnum):
    """Utility Gate (Utility)."""

    THRESHOLD = 0    # float dB
    ATTACK = 1    # float ms
    HOLD = 2    # float ms
    RELEASE = 3    # float ms
    RANGE = 4    # float dB


class SimpleGate(IntEnum):
    """Simple Gate (Utility)."""

    THRESHOLD = 0    # float dB


class Gain(IntEnum):
    """Gain (Utility)."""

    LEVEL = 0    # float dB
    PAN = 1    # float
    PHASE_INVERT = 2    # switch


class Volume(IntEnum):
    """Volume (Utility)."""

    LEVEL = 0    # float %
    CURVE = 1    # switch


class AdaptiveGateSC(IntEnum):
    """Adaptive Gate (S/C) (Utility)."""

    NOISE_REDUCTION = 0    # float %
    SOURCE = 1    # comboBox


class PluginBlend(IntEnum):
    """Plugin Blend (Utility)."""

    INPUTSOURCEID = 0    # int
    INPUTCHANNEL = 1    # int
    STEREOINPUT = 2    # int
    DELAY = 3    # int
    BLEND = 4    # float %
    OUTPUT = 5    # float dB
    SOURCE = 6    # comboBox


class PluginGate(IntEnum):
    """Plugin Gate (Utility)."""

    THRESHOLD = 0    # float dB


class Doubler(IntEnum):
    """Doubler (Utility)."""

    ENABLED = 0    # switch
    SPREAD = 1    # float ms
    DRY_LEVEL = 2    # float dB
    FX_LEVEL = 3    # float dB
    TRIGGER = 4    # comboBox


class PluginDoubler(IntEnum):
    """Plugin Doubler (Utility)."""

    ENABLED = 0    # switch
    SPREAD = 1    # float ms
    DRY_LEVEL = 2    # float dB
    FX_LEVEL = 3    # float dB
    TRIGGER = 4    # comboBox


class TransparentBlend(IntEnum):
    """Transparent Blend (Utility)."""

    INPUTSOURCEID = 0    # int
    INPUTCHANNEL = 1    # int
    STEREOINPUT = 2    # int
    DELAY = 3    # int
    BLEND = 4    # float %
    OUTPUT = 5    # float dB
    SOURCE = 6    # comboBox


class PhaseDoctor(IntEnum):
    """Phase Doctor (Utility)."""

    POLARITY = 0    # switch
    ADJUST = 1    # rotarySwitch
    CENTER = 2    # switch
    SHIFT = 3    # float %
    STEREO_LINK = 4    # switch
    POLARITY_R = 5    # switch
    ADJUST_R = 6    # rotarySwitch
    CENTER_R = 7    # switch
    SHIFT_R = 8    # float %


class PitchShifter(IntEnum):
    """Pitch Shifter (Pitch)."""

    MIX = 0    # float %
    PITCH_COARSE = 1    # float Semitones
    PITCH_FINE = 2    # float Cents


class PolyOctaver(IntEnum):
    """Poly Octaver (Pitch)."""

    DRY = 0    # float %
    OCT = 1    # float %
    SUB = 2    # float %


class Wham(IntEnum):
    """Wham (Pitch)."""

    MIX = 0    # float %
    PEDAL = 1    # float %
    HEEL_PITCH_1 = 2    # float Semitones
    TOE_PITCH_1 = 3    # float Semitones
    HEEL_PITCH_2 = 4    # float Semitones
    TOE_PITCH_2 = 5    # float Semitones
    BLEND = 6    # float %


class Minivoicer(IntEnum):
    """Minivoicer (Pitch)."""

    MIX = 0    # float %
    ROOT = 1    # comboBox
    MODE = 2    # comboBox
    TUNING = 3    # float Hz
    QUANTIZE = 4    # switch
    V1_ACTIVE = 5    # switch
    V1_LEVEL = 6    # float dB
    V1_INTER = 7    # rotarySwitch
    V1_PAN = 8    # float
    V2_ACTIVE = 9    # switch
    V2_LEVEL = 10    # float dB
    V2_INTER = 11    # rotarySwitch
    V2_PAN = 12    # float
    HIGH_PASS = 13    # float Hz
    LOW_PASS = 14    # float Hz
    MIDI = 15    # switch
    GLISSANDO = 16    # float ms
    OUTPUT = 17    # float dB
    V1_NOTE = 18    # float
    V2_NOTE = 19    # float
    V1_SEMIT = 20    # float
    V2_SEMIT = 21    # float
    MIDI_CH = 22    # comboBox
    V1_NOTE_DISPLAY = 23    # float
    V2_NOTE_DISPLAY = 24    # float


class Transpose(IntEnum):
    """Transpose (Pitch)."""

    MIX = 0    # float %
    PITCH_COARSE = 1    # float Semitones
    PITCH_FINE = 2    # float Cents
    SEMITONES = 3    # float Semitones


class PitchCorrection(IntEnum):
    """Pitch Correction (Pitch)."""

    ROOT = 0    # comboBox
    MODE = 1    # comboBox
    TUNING = 2    # float Hz
    QUANTIZE = 3    # float %
    GLISSANDO = 4    # float ms
    HIGH_PASS = 5    # float Hz
    LOW_PASS = 6    # float Hz
    OUTPUT = 7    # float dB


class ChiefOc2(IntEnum):
    """Chief OC2 (Pitch)."""

    OUTPUT = 0    # float dB
    DRY = 1    # float %
    OCT_1 = 2    # float %
    OCT_2 = 3    # float %


class SubharmonicSynth(IntEnum):
    """Subharmonic Synth (Pitch)."""

    OUTPUT = 0    # float dB
    DRY = 1    # float %
    OCTAVE = 2    # float %
    CHARACTER = 3    # float %
    LOW = 4    # float %
    SUB = 5    # float %


class AggiSubOctaver(IntEnum):
    """Aggi Sub Octaver (Pitch)."""

    OUTPUT = 0    # float dB
    CLEAN_LEVEL = 1    # float %
    CLEAN_TONE = 2    # float %
    OCTAVE_LEVEL = 3    # float %
    OCTAVE_FILTER = 4    # float %


class LoveMeat(IntEnum):
    """Love Meat (Filter)."""

    SENSITIVITY = 0    # float
    ATTACK = 1    # float
    DECAY = 2    # float
    COLOR = 3    # float
    INTENSITY = 4    # float
    BLEND = 5    # float
    TRIG_DIRECTION = 6    # switch
    TRIGGER_MODE = 7    # rotarySwitch
    FILTER_CUTOFF = 8    # rotarySwitch
    FILTER_TYPE = 9    # rotarySwitch
    LEVEL = 10    # float dB


class Foog(IntEnum):
    """Foog (Filter)."""

    DRIVE = 0    # float
    DECAY = 1    # switch
    ENV_AMOUNT = 2    # float
    CUTOFF = 3    # float
    RESONANCE = 4    # float
    MIX = 5    # float %
    FILTER = 6    # switch
    LEVEL = 7    # float dB


class EnvelopeFilter(IntEnum):
    """Envelope Filter (Filter)."""

    SENS = 0    # float dB
    ATTACK = 1    # float ms
    DECAY = 2    # float ms
    LP_BP_HP = 3    # float
    LEVEL = 4    # float dB
    FREQ = 5    # float Hz
    FREQ_DEPTH = 6    # float Hz
    RESO = 7    # float
    RESO_ENV_AMT = 8    # float
    MIX = 9    # float %


class EnvelopeFilterSC(IntEnum):
    """Envelope Filter (S/C) (Filter)."""

    SENS = 0    # float dB
    ATTACK = 1    # float ms
    DECAY = 2    # float ms
    LP_BP_HP = 3    # float
    LEVEL = 4    # float dB
    FREQ = 5    # float Hz
    FREQ_DEPTH = 6    # float Hz
    RESO = 7    # float
    RESO_ENV_AMT = 8    # float
    MIX = 9    # float %
    SOURCE = 10    # comboBox


class Freeze(IntEnum):
    """Freeze (Morph)."""

    ON_OFF = 0    # toggleButton
    MOMENTARY = 1    # switch
    ATTACK = 2    # float ms
    RELEASE = 3    # float ms
    DRY_GAIN = 4    # float dB
    FREEZE_GAIN = 5    # float dB
    HIGH_PASS = 6    # float Hz
    LOW_PASS = 7    # float Hz


class PhaseLockedLoop(IntEnum):
    """Phase-Locked Loop (Morph)."""

    OUTPUT = 0    # float dB
    DRY_LEVEL = 1    # float %
    UNISON_LEVEL = 2    # float %
    MUL_LEVEL = 3    # float %
    DIV_LEVEL = 4    # float %
    MUL_SOURCE = 5    # comboBox
    DIV_SOURCE = 6    # comboBox
    MULTIPLIER = 7    # rotarySwitch
    DIVIDER = 8    # rotarySwitch
    RESPONSE = 9    # float %
    STABILITY = 10    # float %
    THRESHOLD = 11    # float dB
    TRAILS_GATE = 12    # switch
    INSTRUMENT = 13    # switch


class BitCrusherSt(IntEnum):
    """Bit-Crusher (ST) (Morph)."""

    OUTPUT = 0    # float dB
    DRY = 1    # float %
    WET = 2    # float %
    RESAMPLER = 3    # float Hz
    BIT_DEPTH = 4    # rotarySwitch bits
    SHAPE = 5    # float %
    TONE = 6    # float Hz


class BitCrusherEngineM(IntEnum):
    """Bit-Crusher Engine (M) (Morph)."""

    OUTPUT = 0    # float dB
    DRY = 1    # float %
    WET = 2    # float %
    RESAMPLER = 3    # float Hz
    FREQ_MULTI = 4    # float
    DISSONANCE = 5    # float %
    PITCH_TRACKING = 6    # switch
    BIT_DEPTH = 7    # rotarySwitch bits
    SHAPE = 8    # float %
    TONE = 9    # float Hz


class LooperX(IntEnum):
    """Looper X (Loopers)."""

    RECORD_OVERDUB = 0    # switch
    PLAY_STOP = 1    # switch
    UNDO = 2    # switch
    DUPLICATE = 3    # switch
    ONE_SHOT = 4    # switch
    HALF_SPEED = 5    # switch
    PUNCH = 6    # switch
    REVERSE = 7    # switch
    PLAYBACK_LEVEL = 8    # float dB
    OVERDUB_LEVEL = 9    # float dB
    HIGH_PASS = 10    # float Hz
    LOW_PASS = 11    # float Hz
    THRESHOLD = 12    # float dB
    RECORD_MODE = 13    # switch
    OVERDUB_MODE = 14    # switch
    DUPLICATE_MODE = 15    # switch
    PUNCH_MODE = 16    # switch
    ROUTING_MODE = 17    # rotarySwitch
    QUANTIZE = 18    # rotarySwitch
    MIDI_CLOCK_START = 19    # switch
    PRE_ROLL = 20    # rotarySwitch
    METRONOME_MUTE = 21    # toggleButton
    REC_LENGTH = 22    # rotarySwitch


class SingleM(IntEnum):
    """Single (M) (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_PAN = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_PAN = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class SingleSt(IntEnum):
    """Single (ST) (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_PAN = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_PAN = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class DualM(IntEnum):
    """Dual (M) (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_PAN = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_PAN = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class DualSt(IntEnum):
    """Dual (ST) (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_BALANCE = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_BALANCE = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class SingleMLite(IntEnum):
    """Single (M) Lite (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_PAN = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_PAN = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class SingleStLite(IntEnum):
    """Single (ST) Lite (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_PAN = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_PAN = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class DualMLite(IntEnum):
    """Dual (M) Lite (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_PAN = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_PAN = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class DualStLite(IntEnum):
    """Dual (ST) Lite (IRLoaders)."""

    IR_1_MUTE = 0    # switch
    IR_1_INVERT = 1    # switch
    IR_1_PATH = 2    # string
    IR_1_LEVEL = 3    # float dB
    IR_1_HI_PASS = 4    # float Hz
    IR_1_LOW_PASS = 5    # float Hz
    IR_1_BALANCE = 6    # float
    IR_1_DELAY = 7    # float ms
    IR_2_MUTE = 8    # switch
    IR_2_INVERT = 9    # switch
    IR_2_PATH = 10    # string
    IR_2_LEVEL = 11    # float dB
    IR_2_HI_PASS = 12    # float Hz
    IR_2_LOW_PASS = 13    # float Hz
    IR_2_BALANCE = 14    # float
    IR_2_DELAY = 15    # float ms
    ROOM_MIX = 16    # float %
    PRE_DELAY = 17    # float ms
    REV_HI_PASS = 18    # float Hz
    REV_LOW_PASS = 19    # float Hz
    SIZE = 20    # rotarySwitch
    GLOBAL_OUTPUT = 21    # float dB
    IR_1_NAME = 22    # string
    IR_2_NAME = 23    # string


class MonoSynth(IntEnum):
    """Mono Synth (Synth)."""

    MIX = 0    # float %
    SENSITIVITY = 1    # float %
    ENV_RETRIGGER = 2    # switch
    TUNING = 3    # float Hz
    QUANTIZE = 4    # switch
    ROOT = 5    # comboBox
    SCALE = 6    # switch
    SYNTH_ACTIVE = 7    # switch
    SYNTH_LEVEL = 8    # float dB
    OSC1_ACTIVE = 9    # switch
    OSC1_WAVE = 10    # rotarySwitch
    OSC_1_LEVEL = 11    # float dB
    OSC_1_STEPS = 12    # float st
    OSC_1_DETUNE = 13    # float %
    OSC2_ACTIVE = 14    # switch
    OSC2_WAVE = 15    # rotarySwitch
    OSC_2_LEVEL = 16    # float dB
    OSC_2_STEPS = 17    # float st
    OSC_2_DETUNE = 18    # float %
    UNISON_SOURCE = 19    # comboBox
    UNI_AMOUNT = 20    # rotarySwitch
    UNI_DETUNE = 21    # float %
    UNI_WIDTH = 22    # float %
    FILTER = 23    # switch
    SLOPE = 24    # rotarySwitch
    CUTOFF = 25    # float Hz
    FILT_MOD = 26    # float %
    RESONANCE = 27    # float %
    DRIVE = 28    # float %
    F_E_AMOUNT = 29    # float %
    F_E_DCY_ATCK = 30    # float ms
    F_E_SUSTAIN = 31    # float %
    ENV_DCY_ATCK = 32    # float ms
    ENV_SUSTAIN = 33    # float %
    GATE = 34    # float dB
    OUTPUT = 35    # float dB
    GLIDE = 36    # float ms
    S_C_SOURCE = 37    # comboBox
    ARPEGGIATOR = 38    # switch
    ARP_PATTERN = 39    # rotarySwitch
    OCTAVE = 40    # rotarySwitch
    ARP_NOTE_2 = 41    # switch
    ARP_NOTE_3 = 42    # switch
    ARP_NOTE_4 = 43    # switch
    ARP_NOTE_5 = 44    # switch
    ARP_NOTE_6 = 45    # switch
    ARP_NOTE_7 = 46    # switch
    ARP_NOTE_8 = 47    # switch
    FREE_RATE = 48    # float Hz
    SYNC = 49    # switch
    SYNC_NOTE = 50    # comboBox
    MIDI_CH = 51    # comboBox
    MIDI_NOTE = 52    # float
    MIDI_VELOCITY = 53    # float
    MIDI_TRIGGER = 54    # switch


class Green808Legacy(IntEnum):
    """Green 808 (Guitar Overdrive)."""

    OVERDRIVE = 0    # float
    TONE = 1    # float
    LEVEL = 2    # float


class Ev101iiisRedEl34100wLegacy(IntEnum):
    """EV101IIIS Red EL34 100W (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    RESONANCE = 6    # float
    OUTPUT = 7    # float dB


class Solo100LeadLegacy(IntEnum):
    """Solo 100 Lead (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class UsDlxNormalLegacy(IntEnum):
    """US DLX Normal (Guitar Amplifier)."""

    VOLUME = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    OUTPUT = 3    # float dB


class UsDlxVibratoLegacy(IntEnum):
    """US DLX Vibrato (Guitar Amplifier)."""

    VOLUME = 0    # float
    BASS = 1    # float
    TREBLE = 2    # float
    OUTPUT = 3    # float dB


class Ev101iiisBlueEl34100wLegacy(IntEnum):
    """EV101IIIS Blue EL34 100W (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    RESONANCE = 6    # float
    OUTPUT = 7    # float dB


class Solo100CrunchBrightLegacy(IntEnum):
    """Solo 100 Crunch Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class Solo100CrunchNormalLegacy(IntEnum):
    """Solo 100 Crunch Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    OUTPUT = 6    # float dB


class DCellH4Ch1BrightLegacy(IntEnum):
    """D-Cell H4 Ch1 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch1NormalLegacy(IntEnum):
    """D-Cell H4 Ch1 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch2BrightLegacy(IntEnum):
    """D-Cell H4 Ch2 Bright (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch2NormalLegacy(IntEnum):
    """D-Cell H4 Ch2 Normal (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch3Legacy(IntEnum):
    """D-Cell H4 Ch3 (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class DCellH4Ch4Legacy(IntEnum):
    """D-Cell H4 Ch4 (Guitar Amplifier)."""

    GAIN = 0    # float
    BASS = 1    # float
    MID = 2    # float
    TREBLE = 3    # float
    MASTER = 4    # float
    PRESENCE = 5    # float
    DEEP = 6    # float
    OUTPUT = 7    # float dB


class Graphic9Legacy(IntEnum):
    """Graphic-9 (Equalizer)."""

    HPF = 0    # float Hz
    N65HZ = 1    # float dB
    N125HZ = 2    # float dB
    N250HZ = 3    # float dB
    N500HZ = 4    # float dB
    N1KHZ = 5    # float dB
    N2KHZ = 6    # float dB
    N4KHZ = 7    # float dB
    N8KHZ = 8    # float dB
    N16KHZ = 9    # float dB
    OUTPUT = 10    # float dB


class PhaserLegacy(IntEnum):
    """Phaser (Modulation)."""

    MIX = 0    # float %
    SPEED = 1    # float
    WIDTH = 2    # float %
    DRIVE = 3    # float %
    SYNC = 4    # switch
    SYNC_NOTE = 5    # rotarySwitch


class NuvibesLegacy(IntEnum):
    """NuVibes (Modulation)."""

    MIX = 0    # float %
    RATE = 1    # float Hz
    INTENSITY = 2    # float %
    WIDTH = 3    # float %
    SHAPE = 4    # float %
    DRIVE = 5    # float %
    SYNC = 6    # switch
    SYNC_NOTE = 7    # rotarySwitch


class BadHorseLegacy(IntEnum):
    """Bad Horse (Wah)."""

    WAH = 0    # float


class EnvelopeFilterLegacy(IntEnum):
    """Envelope Filter (Filter)."""

    SENS = 0    # float dB
    ATTACK = 1    # float ms
    DECAY = 2    # float ms
    LP_BP_HP = 3    # float
    LEVEL = 4    # float dB
    FREQ = 5    # float Hz
    FREQ_ENV_AMT = 6    # float
    RESO = 7    # float
    RESO_ENV_AMT = 8    # float
    MIX = 9    # float %


class EnvelopeFilterSCLegacy(IntEnum):
    """Envelope Filter (S/C) (Filter)."""

    SENS = 0    # float dB
    ATTACK = 1    # float ms
    DECAY = 2    # float ms
    LP_BP_HP = 3    # float
    LEVEL = 4    # float dB
    FREQ = 5    # float Hz
    FREQ_ENV_AMT = 6    # float
    RESO = 7    # float
    RESO_ENV_AMT = 8    # float
    MIX = 9    # float %
    SOURCE = 10    # comboBox


#: Every generated enum, keyed by the model id it describes.
BY_MODEL = {
    1: MythDrive,
    2: ObsessiveDrive,
    3: Od250,
    4: RodentDrive,
    6: Exotic,
    8: FreemanBod,
    9: BritBlues,
    10: ChiefDs1,
    11: BritGovernor,
    12: ChiefMt,
    13: ChiefOd1,
    14: ChiefSd1,
    15: FuzzPi,
    18: ChiefBd2,
    21: RageBooster,
    22: FacialFuzz,
    23: ExoticZBoost,
    24: RedDrive,
    25: VemuralRay,
    26: NoBellOd1,
    27: Green808,
    28: Thunderpaw,
    29: Mk3SiliconFuzz,
    42: N81CreationsDrive,
    1001: Brit2203,
    1002: Pv505Lead,
    1008: RolsJazzCh120,
    1009: UkC30Normal,
    1011: UkC30Topboost,
    1018: CaDuoCh3Modern,
    1019: CaDuoCh3Raw,
    1020: CaDuoCh3Vintage,
    1027: Freeman100Clean,
    1028: Freeman100Rhythm,
    1038: BritTm45Normal,
    1039: BritTm45Bright,
    1040: BritTm45Patch,
    1041: Brit900Clean,
    1042: Brit900Lead,
    1063: WattD103Normal,
    1064: WattD103Bright,
    1079: BritPlexi50Bright,
    1080: BritPlexi50Patch,
    1081: BritPlexi50Normal,
    1082: Freeman100Lead,
    1083: UsTwnNormal,
    1084: UsTwnVibrato,
    1089: CaTremoOrange,
    1090: CaTremoRed,
    1091: BritPlexi100Bright,
    1092: BritPlexi100Patch,
    1093: BritPlexi100Normal,
    1096: UsSprNormal,
    1097: UsSprVibrato,
    1101: Ca1starClean50wNormal,
    1102: Ca1starClean50wTweed,
    1103: Ca1starClean100wNormal,
    1104: Ca1starClean100wTweed,
    1105: Ca1starDrive50wNormal,
    1106: Ca1starDrive50wTweed,
    1107: Ca1starDrive100wNormal,
    1108: Ca1starDrive100wTweed,
    1115: Pv505Rhythm,
    1116: Captain50,
    1117: BognaVishnu20thClean,
    1118: Ev101iiisBlue6l6100w,
    1119: Ev101iiisRed6l6100w,
    1120: UsPrince,
    1121: BritUblLead,
    1122: BritUblLeadClip,
    1123: UsTweedBassladBrightPatch,
    1124: UsTweedBassladBright,
    1125: UsTweedBassladNormalPatch,
    1126: UsTweedBassladNormal,
    1127: UkC15Normal,
    1128: UkC15Topboost,
    1132: UsHpTweedTwnNormal,
    1133: UsHpTweedTwnNormalPatch,
    1134: UsHpTweedTwnBright,
    1135: UsHpTweedTwnBrightPatch,
    1136: DCellHisbertCh1,
    1137: DCellHisbertCh2,
    1138: DCellHisbertCh3,
    1139: CaJohnS2cCh1,
    1140: CaJohnS2cCh2,
    1141: CaJohnS2cCh3,
    1142: DCellH4Ch1Bright,
    1143: DCellH4Ch1Normal,
    1144: DCellH4Ch2Bright,
    1145: DCellH4Ch2Normal,
    1146: DCellH4Ch3,
    1147: DCellH4Ch4,
    1148: Ev101iiisRedEl34100w,
    1149: Ev101iiisBlueEl34100w,
    1150: Solo100Lead,
    1151: Solo100CrunchBright,
    1152: Solo100CrunchNormal,
    1154: MatchmoreJefe,
    1155: MatchmoreD30Ch1,
    1156: MatchmoreD30Ch2,
    1157: VictorSquidCh1,
    1158: VictorSquidCh2,
    1166: UsDlx64Vintage,
    1167: UsDlx65Reissue,
    1176: DumbbellOds,
    2010: BritBass50Bright,
    2011: BritBass50Patch,
    2012: BritBass50Normal,
    2013: G800k,
    2014: Ca400Ch1,
    2015: Ca400Ch2,
    2016: AmpedSuperValve,
    2017: AmpedFlipTop6464,
    2018: AmpedFlipTop6466,
    2019: AmpedFlipTop6664,
    2020: AmpedFlipTop6666,
    2021: WattBassModNormal,
    2022: WattBassModBright,
    3000: MicrotubesB3k,
    3001: Bddi,
    3004: SovietFuzz,
    3006: MicrotubesVmt,
    3007: ExoticBassZBoost,
    4000: Parametric8,
    4001: Parametric3,
    4003: LowHighCut,
    4005: Graphic9,
    4006: PluginGraphic9,
    5001: Legendary87M,
    5004: SolidStateCompM,
    5005: VcaCompM,
    5007: OptoCompM,
    5011: Jewel,
    5012: Legendary87St,
    5013: SolidStateCompSt,
    5014: VcaCompSt,
    5015: OptoCompSt,
    5016: ChiefCs3,
    5018: SolidStateCompSC,
    5019: Legendary87SC,
    5020: OptoCompSC,
    5021: VcaCompSC,
    6001: AnalogDelayM,
    6002: SimplePingPongDelay,
    6003: SimpleDelaySt,
    6004: TapeDelaySt,
    6005: DigitalDelayM,
    6006: SimpleDelayM,
    6007: TapeDelayM,
    6008: SlapbackDelaySt,
    6009: SlapbackDelayM,
    6010: AnalogDelaySt,
    6011: DigitalDelaySt,
    6012: DualDelay,
    6013: ReverseDelayM,
    6014: DualReverseDelay,
    6015: CircularDelay,
    7000: VintageChorus,
    7001: DualChorus,
    7002: Vibrato,
    7003: Flangerish,
    7004: Tremolo,
    7008: Rotary,
    7009: DigitalFlanger,
    7014: FlangerEngine,
    7015: ChorusEngine,
    7021: MxFlanger,
    7022: DreamChorusSt,
    7023: Chorus229t,
    7024: ChiefCe2wSt,
    7025: ChiefCe2wM,
    7026: DreamChorusM,
    7027: ChiefDc2wSt,
    7028: MxPhase95,
    7029: MxVibe,
    7030: ChiefDc2wM,
    7031: Phaser,
    7036: HarmonicTremolo,
    7039: MicroProcessorSt,
    7040: PatternTremolo,
    8000: Room,
    8001: SpringSt,
    8003: Hall,
    8006: SpringM,
    8007: Modulated,
    8008: Ambience,
    8009: Cave,
    8010: Shimmer,
    8011: MindHall,
    8012: PlateLush,
    8013: Plate,
    8014: PlateTight,
    8026: SpringReverbEngineM,
    8027: SpringReverbEngineSt,
    8028: NordicConcertHallSt,
    8029: StudioPlate70St,
    8030: BlossomSt,
    9010: BubbaWah,
    9012: BassWah,
    9013: CryingWah,
    9014: CryingClydeWah,
    9018: BadHorse,
    9019: CryingWahFromHell,
    9021: AutoWah,
    13000: Send1,
    13001: Send2,
    13002: Return1,
    13003: Return2,
    13004: FxLoop1,
    13005: FxLoop2,
    13006: Send12,
    13007: Return12,
    13008: FxLoop12,
    16001: AdaptiveGate,
    16002: UtilityGate,
    16003: SimpleGate,
    16005: Gain,
    16006: Volume,
    16007: AdaptiveGateSC,
    16008: PluginBlend,
    16009: PluginGate,
    16011: Doubler,
    16012: PluginDoubler,
    16013: TransparentBlend,
    16016: PhaseDoctor,
    18001: PitchShifter,
    18004: PolyOctaver,
    18006: Wham,
    18007: Minivoicer,
    18010: Transpose,
    18013: PitchCorrection,
    18014: ChiefOc2,
    18015: SubharmonicSynth,
    18016: AggiSubOctaver,
    24001: LoveMeat,
    24002: Foog,
    24006: EnvelopeFilter,
    24007: EnvelopeFilterSC,
    26001: Freeze,
    26002: PhaseLockedLoop,
    26003: BitCrusherSt,
    26004: BitCrusherEngineM,
    27000: LooperX,
    29001: SingleM,
    29002: SingleSt,
    29003: DualM,
    29004: DualSt,
    29005: SingleMLite,
    29006: SingleStLite,
    29007: DualMLite,
    29008: DualStLite,
    30001: MonoSynth,
    5: Green808Legacy,
    1017: Ev101iiisRedEl34100wLegacy,
    1045: Solo100LeadLegacy,
    1094: UsDlxNormalLegacy,
    1095: UsDlxVibratoLegacy,
    1098: Ev101iiisBlueEl34100wLegacy,
    1099: Solo100CrunchBrightLegacy,
    1100: Solo100CrunchNormalLegacy,
    1109: DCellH4Ch1BrightLegacy,
    1110: DCellH4Ch1NormalLegacy,
    1111: DCellH4Ch2BrightLegacy,
    1112: DCellH4Ch2NormalLegacy,
    1113: DCellH4Ch3Legacy,
    1114: DCellH4Ch4Legacy,
    4002: Graphic9Legacy,
    7006: PhaserLegacy,
    7007: NuvibesLegacy,
    9017: BadHorseLegacy,
    24003: EnvelopeFilterLegacy,
    24004: EnvelopeFilterSCLegacy,
}
